### ISSUE TITLE
water leg broken

### ISSUE THREAD

**Issue by xy21hb** [luancarvalhomartins/PyAutoFEP#101]
Dear all,

I have got error like below. Quite different from previous common errors, I only have errors from the water system leg,
![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/14272986/b59d8e2a-c62c-4b4c-8666-e73a82a32823)

For each transformation, e.g. FXR_12 ---> FXR_88, I go to  /PyAutoFEP-master/docs/tutorial01/tutorial1/FXR_12-FXR_88/water/md,
l can have logs like below, I checked the feprun_... log and reren_joblog_....log, there is no notable error msg inside,
![屏幕截图 2023-07-17 174410](https://github.com/luancarvalhomartins/PyAutoFEP/assets/14272986/27be7bb4-09b3-4e0c-a2fd-addec81fa9ab)

However, there is nothing in /analysis, there seems to be no traj or analysis generated. Moreover, in /rerun, I can have files like,  
 
![屏幕截图 2023-07-17 174329](https://github.com/luancarvalhomartins/PyAutoFEP/assets/14272986/82fc90c7-b347-43c1-b7b7-ab90f7c3b909)

However, in the counterpart of protein leg, everything seems to be okay, 

![屏幕截图 2023-07-17 174556](https://github.com/luancarvalhomartins/PyAutoFEP/assets/14272986/3e4a8e71-c310-4a53-9e29-2cf33a73c7fc)

So why does the water leg only have problems, but not protein leg? Thanks!

**Comment by luancarvalhomartins** [comment]
From your first image, it seems the water leg did not run. Would you mind checking the `gmx mdrun` logs for the water leg?

**Comment by xy21hb** [comment]
[mdout_nocont.log](https://github.com/luancarvalhomartins/PyAutoFEP/files/12115372/mdout_nocont.log)
[mdout.log](https://github.com/luancarvalhomartins/PyAutoFEP/files/12115373/mdout.log)

Above are the md files, e.g. under /PyAutoFEP-master/docs/tutorial01/tutorial1/FXR_12-FXR_88/water/lambda11/md.
============================
Below are lambda files, e.g. under PyAutoFEP-master/docs/tutorial01/tutorial1/FXR_12-FXR_88/water/md/lambda11,
[lambda.log](https://github.com/luancarvalhomartins/PyAutoFEP/files/12115424/lambda.log)

I also noticed in this directory, plumed.dat has nothing inside.

**Comment by xy21hb** [comment]
Dear Luan,
Attached are the md files, e.g. under /PyAutoFEP-master/docs/tutorial01/tutorial1/FXR_12-FXR_88/water/lambda11/md.
The last files are lambda files, e.g. under PyAutoFEP-master/docs/tutorial01/tutorial1/FXR_12-FXR_88/water/md/lambda11,
lambda.log

I also noticed in this directory, plumed.dat has nothing inside.

Best,
YAO
________________________________

**Comment by luancarvalhomartins** [comment]
Thank you for the detailed information.

The lambda.log shows you are running only 0.6 ps (`nsteps = 300`, `dt = 0.002`). Because `nstxout = 1000`, you only get 1 frame. PyAutoFEP was able to rerun and collect data even using a single frame! On a second thought, I think everything worked (to the extent it could be possible). If the error you are concerned about is the `tar` one, that's harmless.

What are you trying to do, exactly?

**Comment by xy21hb** [comment]
Dear Luan,

Many thanks for your reply.

Yes, I understand that the windows are short and meaningless to get statistics. All I want to do is just to test the workflow on a single non-cluster local desktop using serial run. Since regular calculations takes much time and it is hard to get error message if there are errors in the middle of the runs.

I extended the simulation length to longer times below. Still it has the same problem, i.e. the water leg do not have anything under analysis.
I wonder why only water leg has this problem specifically, but not the protein-ligand complex leg, no matter how small the lambda window is.



[cid:4ce6bc42-f5f9-4088-8837-bb74535c6638]

However, it seems to be working for analyze_results.py,

[cid:fdd94285-7c5d-4ff6-9897-636b5dfb534e]

Of course, those ddG might be meaningless due to short windows.

Best,
Yao
________________________________

**Comment by xy21hb** [comment]
![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/14272986/49d82c9c-9fbf-402c-aeac-b30be865db9e)

![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/14272986/07b77be5-a915-4824-a70f-b8d6fa713720)

**Comment by luancarvalhomartins** [comment]
Currently, no analysis is performed for water leg. I hope I find time to add that in the future.

From your last message, it seems everything seems to be working fine.
