### ISSUE TITLE
`analyze_results.py`: Could not find a path to connect nodes AAA and BBB. Cannot go on.

### ISSUE THREAD

**Issue by Liaokang123456** [luancarvalhomartins/PyAutoFEP#102]
After I finished the "run runall.sh", I got the file "tutorial.tgz";
and I run “analyze_results.py --input tutorial.tgz --units kcal --output_uncompress_directory tutorial --center_molecule=FXR_12”
then I got the error like this,
![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/18612096/797b9971-0411-42fe-8762-b63374303f86)

My gromacs version : gmx_mpi 2021.7 
alchemlyb_version 0.6.0

**Comment by VesperChen01** [comment]
I'm having the same problem.

$ analyze_results.py --input tutorial.tgz --units kcal --output_uncompress_directory tutorial --center_molecule=C-7
All available analysis will be run
================== Pairwise ΔΔG ==================
         Perturbation           protein    water
         C-7→d-2           -5.3±0.1 kcal/mol    -4.9±0.1 kcal/mol   ΔΔG = -0.4±0.1 kcal/mol

=================== STACK INFO ===================
  File "./analyze_results.py", line 1821, in <module>
    method=arguments.center_ddg_method)
  File "./analyze_results.pyanalyze_results.py", line 1039, in ddg_to_center_ddg
    current_verbosity=verbosity)
  File "./analyze_results.pyos_util.py", line 307, in local_print
    formatted_string = '\n{:=^50}\n{}{:=^50}\n'.format(' STACK INFO ', ''.join(traceback.format_stack()),
=================== STACK INFO ===================
[ERROR] Could not find a path to connect nodes C-15 and C-7. Cannot go on. Check the  perturbations and your input graph. Alternatively, rerun with no_checks to force execution and ignore this error.
Traceback (most recent call last):
  File "./analyze_results.pyanalyze_results.py", line 1024, in ddg_to_center_ddg
    ddg_to_center[each_node] = sum_path(ddg_graph, each_path, ddg_key=ddg_key)
  File "./analyze_results.pyanalyze_results.py", line 986, in sum_path
    raise networkx.exception.NetworkXNoPath('Edge between {} {} not found in graph {}'.format(node_i, node_j, g0))
networkx.exception.NetworkXNoPath: Edge between C-7 C-15 not found in graph DiGraph with 6 nodes and 5 edges

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./analyze_results.pyanalyze_results.py", line 1821, in <module>
    method=arguments.center_ddg_method)
  File "./analyze_results.pyanalyze_results.py", line 1040, in ddg_to_center_ddg
    raise networkx.exception.NetworkXNoPath(error)
networkx.exception.NetworkXNoPath: Edge between C-7 C-15 not found in graph DiGraph with 6 nodes and 5 edges

**Comment by VesperChen01** [comment]
@Liaokang123456                                                                                                              After checking the log file, I found a segmentation fault, which may be caused by a system crash during the gmx_mpi runtime. Therefore, the task was not fully completed in runall.sh. Please check the integrity of the files in each lambda* folder in the md file, such as *.gro. If any files are missing, you can simply rerun the commands in the runall.sh folder.

"Please let me know if there are any mistakes."

**Comment by luancarvalhomartins** [comment]
These errors are caused by the lack of data for the perturbations in the error. It means something went wrong with the FEP. Please, check the logs to see why.

I apologize for the output being cryptic. I am rewriting that message to make it more informative.

**Comment by luancarvalhomartins** [comment]
Please, feel free to fill a new issue in case the FEP problem seems a bug.

Thank you!
