### ISSUE TITLE
MD crashes

### ISSUE THREAD

**Issue by VesperChen01** [luancarvalhomartins/PyAutoFEP#107]
I have 10 molecules, and three or four of them have anomalies. However, during the topological and related processes, the parameter settings are the same for all molecules. Due to structural anomalies in some molecules (as shown in the figure, where the benzene ring should be normal), it leads to 'segmentation fault (MD crashes)' during the 'runall.sh' step.

![jpg](https://github.com/luancarvalhomartins/PyAutoFEP/assets/103991971/102fd973-1333-4980-9f95-9e44dcacfa33)

**Comment by luancarvalhomartins** [comment]
The PDB that is passed to GROMACS contains atoms of both topologies A and B. PyMol assigns bond based on the distance between atoms, regardless of which of the topologies A and B they belong to. Therefore, what you are seeing is an artifact of the PyMol representation.

Are you observing segmentation faults in GROMACS or is your system blowing up? In the later case, double check the MCS between the molecules and the number of perturbed atoms. In case everything seems fine, try running using more lambda windows.

**Comment by VesperChen01** [comment]
**1.** This is 'feprun_133410_03082023.log'. 

Step 12452, time 24.904 (ps)  LINCS WARNING in simulation 1
relative constraint deviation after LINCS:
rms 0.071517, max 2.333266 (between atoms 3684 and 3685)
bonds that rotated more than 30 degrees:
 atom 1 atom 2  angle  previous, current, constraint length
   3684   3685   90.0    0.1080   0.3600      0.1080
   4089   4076   90.0    0.1090   0.3521      0.1090
   4089   4076   90.0    0.1090   0.3521      0.1090
   4089   4076   90.0    0.1090   0.3521      0.1090
   4089   4076   90.0    0.1090   0.3521      0.1090
   4089   4076   90.0    0.1090   0.3521      0.1090
   4089   4076   90.0    0.1090   0.3521      0.1090
   4089   4076   90.0    0.1090   0.3521      0.1090

step 12400, will finish Thu Aug  3 17:36:16 2023Wrote pdb files with previous and current coordinates

Step 12453, time 24.906 (ps)  LINCS WARNING in simulation 1
relative constraint deviation after LINCS:
rms 0.856589, max 32.602646 (between atoms 3684 and 3685)
bonds that rotated more than 30 degrees:
 atom 1 atom 2  angle  previous, current, constraint length
   3678   3679   90.0    0.1090   2.3710      0.1090
   3680   3681   41.1    0.1090   0.1089      0.1090
   3680   3682   90.0    0.1090   0.2196      0.1090
   3684   3685   90.0    0.3600   3.6291      0.1080
   4089   4076   62.9    0.3521   0.1088      0.1090
   4089   4076   62.9    0.3521   0.1088      0.1090
   4089   4076   62.9    0.3521   0.1088      0.1090
   4089   4076   62.9    0.3521   0.1088      0.1090
   4089   4076   62.9    0.3521   0.1088      0.1090
   4089   4076   62.9    0.3521   0.1088      0.1090
   4089   4076   62.9    0.3521   0.1088      0.1090
Wrote pdb files with previous and current coordinates

Step 12454, time 24.908 (ps)  LINCS WARNING in simulation 1
relative constraint deviation after LINCS:
rms 155306.125000, max 4049294.750000 (between atoms 926 and 927)
bonds that rotated more than 30 degrees:
 atom 1 atom 2  angle  previous, current, constraint length
    924    925   55.0    0.1090   0.1090      0.1090
    926    927   48.2    0.1090 441373.2188      0.1090
    926    928   63.9    0.1090 440992.7188      0.1090
   3678   3679  168.9    2.3710 440973.5625      0.1090
   3680   3681   90.0    0.1089   0.1479      0.1090
   3680   3682   81.6    0.2196   0.1045      0.1090
   3684   3685  128.4    3.6291   8.2821      0.1080
   4089   4076   90.0    0.1088   0.3150      0.1090
   4089   4076   90.0    0.1088   0.3150      0.1090
   4089   4076   90.0    0.1088   0.3150      0.1090
   4089   4076   90.0    0.1088   0.3150      0.1090
   4089   4076   90.0    0.1088   0.3150      0.1090
   4089   4076   90.0    0.1088   0.3150      0.1090
   4089   4076   90.0    0.1088   0.3150      0.1090
Wrote pdb files with previous and current coordinates

Step 12455, time 24.91 (ps)  LINCS WARNING in simulation 1
relative constraint deviation after LINCS:
rms 310620.750000, max 8098798.000000 (between atoms 926 and 927)
bonds that rotated more than 30 degrees:
 atom 1 atom 2  angle  previous, current, constraint length
    924    925   90.0    0.1090   0.1254      0.1090
    929    930   90.0    0.1090   0.1597      0.1090
    929    931   90.0    0.1090   0.1512      0.1090
   3676   3677   90.0    0.1010   0.4017      0.1010
   3680   3681  109.9    0.1479  32.9508      0.1090
   3680   3682  133.1    0.1045  32.1523      0.1090
   3690   3691   96.0    0.1080  29.0857      0.1080
   4089   4076   64.3    0.3150   0.1089      0.1090
   4089   4076   64.3    0.3150   0.1089      0.1090
   4089   4076   64.3    0.3150   0.1089      0.1090
   4089   4076   64.3    0.3150   0.1089      0.1090
   4089   4076   64.3    0.3150   0.1089      0.1090
   4089   4076   64.3    0.3150   0.1089      0.1090
   4089   4076   64.3    0.3150   0.1089      0.1090

step 12500, will finish Thu Aug  3 17:35:59 2023Wrote pdb files with previous and current coordinates

Step 12456, time 24.912 (ps)  LINCS WARNING in simulation 1
relative constraint deviation after LINCS:
rms 470287.593750, max 12148295.000000 (between atoms 926 and 927)
bonds that rotated more than 30 degrees:
 atom 1 atom 2  angle  previous, current, constraint length
    658    659   90.0    0.1090   1.4800      0.1090
    658    660   35.6    0.1090   0.1131      0.1090
    924    925   90.0    0.1254   4.5405      0.1090
    929    930   90.0    0.1597   0.1821      0.1090
    929    931   90.0    0.1512   0.1524      0.1090
   1676   1677  147.3    0.1090 1724.5902      0.1090
   2059   2060   90.0    0.1090   0.2767      0.1090
   2059   2061   90.0    0.1090   0.2799      0.1090
   2059   2062  144.4    0.1090 171431.3906      0.1090
   3574   3575   90.0    0.1090   3.2540      0.1090
   3647   3648   75.0    0.1010 18657.6113      0.1010
   3649   3650   90.0    0.1090   0.2782      0.1090
   3649   3651   90.0    0.1090   0.2322      0.1090
   3668   3669   90.0    0.1090   0.3968      0.1090
   3676   3677  116.6    0.4017 12313.8086      0.1010
   3680   3682  113.1   32.1523 1701.8857      0.1090
   3686   3687   90.0    0.1080   0.2152      0.1080
   3688   3689   90.0    0.1080   0.1184      0.1080
   3690   3691  110.9   29.0857 259555.5000      0.1080
   3693   3694   90.0    0.0945   0.4423      0.0945
   3719   3720   98.8    0.1010 3540.3989      0.1010
   3721   3722   90.0    0.1090   0.1695      0.1090
   4089   4076   90.0    0.1089   0.3025      0.1090
   4089   4076   90.0    0.1089   0.3025      0.1090
   4089   4076   90.0    0.1089   0.3025      0.1090
   4089   4076   90.0    0.1089   0.3025      0.1090
   4089   4076   90.0    0.1089   0.3025      0.1090
   4089   4076   90.0    0.1089   0.3025      0.1090
   4089   4076   90.0    0.1089   0.3025      0.1090

step 12456: One or more water molecules can not be settled.
Check for bad contacts and/or reduce the timestep if appropriate.
Wrote pdb files with previous and current coordinates
[DESKTOP-FV9G3UP:162792] *** Process received signal ***
[DESKTOP-FV9G3UP:162792] Signal: Segmentation fault (11)
[DESKTOP-FV9G3UP:162792] Signal code: Address not mapped (1)
[DESKTOP-FV9G3UP:162792] Failing at address: 0x55ed2f4b2608
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------


Received the TERM signal, stopping within 100 steps



Received the TERM signal, stopping within 100 steps



Received the TERM signal, stopping within 100 steps



Received the TERM signal, stopping within 100 steps



Received the TERM signal, stopping within 100 steps



Received the TERM signal, stopping within 100 steps


step 12600, will finish Thu Aug  3 17:35:53 2023
step 12700, will finish Thu Aug  3 17:35:39 2023

Received the TERM signal, stopping within 100 steps



Received the TERM signal, stopping within 100 steps



Received the TERM signal, stopping within 100 steps



Received the TERM signal, stopping within 100 steps



Received the TERM signal, stopping within 100 steps

--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node DESKTOP-FV9G3UP exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------

**2.** Many pdb files have been generated in the path tutorial/C-7-d-9/protein/md/lambda1/.

![1691041234263](https://github.com/luancarvalhomartins/PyAutoFEP/assets/103991971/018e0080-9b01-4651-ba3b-4a51fec38a36)


--------------------
I may not fully understand the script, please provide me with more detailed questions and solutions. If it's too concise, I may not be able to comprehend it. Thank you!

@luancarvalhomartins

**Comment by xy21hb** [comment]
the system seemingly is not properly energy minimized. All those step1245*.pdbs are GROMACS intermediate files. So check your system carefully, esp. solvation and try to run longer minimization and LINCS_order in your em.mdp.

**Comment by luancarvalhomartins** [comment]
Your system is blowing up.
1. Is your topology correct? Make sure to check, as this is the most likely problem.
    * Also check the MCS and the perturbed region, make sure it is correct.
2. In case everything is fine, you may try:
    * Running a longer minimization (as suggested by @xy21hb)
    * Using a longer equilibration
    * Using more lambda windows

For anyone reading this in the future, this is hardly a PyAutoFEP bug, but rather a system-specific issue.  Use the check list above to guide you in diagnosing.
