### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by baba-hashimoto** [luancarvalhomartins/PyAutoFEP#11]
I found a mistake in output_files_data.ini.
I think line 199 should be changed as follows.
 ( parallel --jobs=$n_jobs '__GMXBIN__ distance -select '\''com of group LIG plus com of group Protein'\'' -f {.} _pbcfit.xtc -s {} -n ... /__INDEX__ -oall analysis/{//}_protligdist.xvg >> {//}/analysis.log 2>&1' ::: ${trajectory_files} ) || { echo "Failed to calculate distance between ligand and protein on line $LINENO"; }
Could you check  the script ?

**Comment by luancarvalhomartins** [comment]
Thanks for the report. Fixed in fa6c1c9.

**Comment by baba-hashimoto** [comment]
Thanks for your quick response.
