### ISSUE TITLE
rename_res.sh not found

### ISSUE THREAD

**Issue by futianfan** [luancarvalhomartins/PyAutoFEP#111]
Thanks for your great work. I do not find the script "rename_res.sh", would you mind sharing it? THanks so much!

**Comment by xy21hb** [comment]
Untar PyAutoFEP-master/docs/tutorial01/workdir.tar and it is PyAutoFEP-master/docs/tutorial01/rename_res.sh

**Comment by futianfan** [comment]
thanks so much for your help!
