### ISSUE TITLE
Resolution of XTC Generation Issue in run.sh with 'echo' Command Enhancement

### ISSUE THREAD

**Issue by AzraelXu** [luancarvalhomartins/PyAutoFEP#114]
![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/71536738/7c606e06-535b-443a-b043-798d3a8c997b)

I encountered an issue while generating the XTC trajectory using run.sh. After analyzing the ../md/lambda11/analysis.log file, I found that there was an error in the echo command used to select the system. 

[analysis.log](https://github.com/luancarvalhomartins/PyAutoFEP/files/12434751/analysis.log)

![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/71536738/16a209ea-8a7d-475a-94fc-74d2af481fe2)

To address this, I suggest adding the -e option after the echo command.

Best regards,

Xu

![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/71536738/a193c851-e1d6-40ee-96e4-83d8a8cd493f)

**Comment by AzraelXu** [comment]
![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/71536738/bfef3cd8-5655-4bb7-8d65-3a25ac2e96d0)
![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/71536738/62ad08bc-6146-4daf-904c-5fb82c45d84e)

While I successfully resolved the issue in the 'protein leg,' I am still encountering the problem of missing XTC files in the 'water leg.' I am curious to understand the underlying cause of this persistent issue.

**Comment by xy21hb** [comment]
try to run analyze_results.py step.

**Comment by AzraelXu** [comment]
> try to run analyze_results.py step.

analyze_results.py is working fine, and I have obtained the computed results. I'm just curious about how to resolve this error. After all, the author must have had a specific purpose in mind when including this command.
![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/71536738/9d301fae-0664-485a-9d54-51961517bec3)

**Comment by luancarvalhomartins** [comment]
I am a bit confused. The current version of `dist/output_files_data.ini` uses `printf`:

```sh
printf "System\n" | __GMXBIN__ trjconv -f lambda_fit2.xtc -s lambda.tpr -o lambda_frame0.pdb -dump 0 -n ../../__INDEX__ >> analysis.log 2>&1
printf "C-alpha\nSystem\n" | __GMXBIN__ trjconv -f lambda_fit2.xtc -s lambda_frame0.pdb -o lambda_fit3.xtc -pbc nojump -n ../../__INDEX__ -center >> analysis.log 2>&1
printf "C-alpha\nSystem\n" | __GMXBIN__ trjconv -f lambda_fit3.xtc -s lambda.tpr -o lambda_fit4.xtc -center -n ../../__INDEX__ >> analysis.log 2>&1
printf "System\n" | __GMXBIN__ trjconv -f lambda_fit4.xtc -s lambda.tpr -o lambda_fit5.xtc -pbc mol -ur compact -n ../../__INDEX__ >> analysis.log 2>&1
printf "C-alpha\nC-alpha\nSystem\n" | __GMXBIN__ trjconv -f lambda_fit5.xtc -s lambda.tpr -o lambda_pbcfit.xtc -fit rot+trans -center -n ../../__INDEX__ >> analysis.log 2>&1
```

Could you confirm that you are using an up-to-date version of PyAutoFEP?

The purpose of these commands is correcting the PBC so that geometric analysis makes sense. The purpose of that `tar` is to save run data to be easly copied back from your cluster/cloud. It is also an input (but not the only one) to `analyze_results.py`.

**Comment by AzraelXu** [comment]
> I am a bit confused. The current version of `dist/output_files_data.ini` uses `printf`:
> 
> ```shell
> printf "System\n" | __GMXBIN__ trjconv -f lambda_fit2.xtc -s lambda.tpr -o lambda_frame0.pdb -dump 0 -n ../../__INDEX__ >> analysis.log 2>&1
> printf "C-alpha\nSystem\n" | __GMXBIN__ trjconv -f lambda_fit2.xtc -s lambda_frame0.pdb -o lambda_fit3.xtc -pbc nojump -n ../../__INDEX__ -center >> analysis.log 2>&1
> printf "C-alpha\nSystem\n" | __GMXBIN__ trjconv -f lambda_fit3.xtc -s lambda.tpr -o lambda_fit4.xtc -center -n ../../__INDEX__ >> analysis.log 2>&1
> printf "System\n" | __GMXBIN__ trjconv -f lambda_fit4.xtc -s lambda.tpr -o lambda_fit5.xtc -pbc mol -ur compact -n ../../__INDEX__ >> analysis.log 2>&1
> printf "C-alpha\nC-alpha\nSystem\n" | __GMXBIN__ trjconv -f lambda_fit5.xtc -s lambda.tpr -o lambda_pbcfit.xtc -fit rot+trans -center -n ../../__INDEX__ >> analysis.log 2>&1
> ```
> 
> Could you confirm that you are using an up-to-date version of PyAutoFEP?
> 
> The purpose of these commands is correcting the PBC so that geometric analysis makes sense. The purpose of that `tar` is to save run data to be easly copied back from your cluster/cloud. It is also an input (but not the only one) to `analyze_results.py`.

Thank you for your answer and effort for this project .
I change 'printf' to echo because of below issue.

Error creating */water/md/analysis/*.xvg file 

> #69

**Comment by xiaohongniua2** [comment]
Thanks for your effort for this project ..
I used the latest code of PyAutoFEP, and got an error as shown during **bash pack.sh**. Though analyze_results.py  can be executed without errors.

After trouble shooting, I found no .txc files were generated in  */water/md/lambda*/

**My questions:**
Are .txc files used in analyze_results.py? Are these .txc files related to caculate ddg? 
If yes, how can we get these  .txc files?
If no, pack.sh might be ajusted as following:
`
#!/bin/bash

tar --create --gzip --file tutorial.tgz */{water,protein}/md/rerun/{*.pkl,*.xvg,*.edr} \
*/protein/md/lambda*/lambda{_pbcfit.xtc,_nocont.tpr,.tpr,.log,.edr} \
#*/water/md/lambda*/lambda{.xtc,_nocont.tpr,.tpr,.log,.edr} \
*/water/md/lambda*/lambda{_nocont.tpr,.tpr,.log,.edr} \
*/protein/md/lambda*/analysis.log \
*/{water,protein}/{*.ndx,*.itp,*.top,*.atp,*.pdb} \
*.pkl
`

![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/53455633/dc912b5b-2bfa-40ff-a12f-d7e1f2d0afb9)

**Comment by xiaohongniua2** [comment]
After futher trouble shooting, if i understand corectly, these .txc files might be generated during trjconv,  which were used for geometric analysis, not related to caculate ddg?. 

trjconv was included in **runall_FXR_12-FXR_76_protein.sh** but not in **runall_FXR_12-FXR_76_water.sh** in the newest codes. which might mean that Geometric analysis was only done for protein leg, not for water leg, in analyze_results.py. 

That might be the reason that analyze_results.py can be executed without errors though `tar: */water/md/lambda*/lambda.xtc: Cannot stat: No such file or directory` was reported in pack.sh.
