### ISSUE TITLE
Problems with using Cgenff topologies

### ISSUE THREAD

**Issue by pallavsen007** [luancarvalhomartins/PyAutoFEP#116]
Most of the CGenFF topologies are built using mol2 files to get the str and itp files respectively. And after that if one has to go through the PyAutoFEP tool, one essentially has to build 'mol' files again especially from SMILES which is convenient using this tool, but again there are problems with the atom naming. 
It would be wise to parameterize directly from the mol files to get cgenff topologies then build the dual topology using 'prepare_dual_topology'.

**Comment by luancarvalhomartins** [comment]
Sorry, I did not quite follow your suggestion.

PyAutoFEP is able to handle .mol2 files. The recommended way to use CGenFF topologies is to parameterize your molecules then pass the output .str and .mol2 files to `prepare_dual_topology.py`. See the manual, section 3.3, for more info.

**Comment by pallavsen007** [comment]
ok. I was misunderstanding it. Thanks a lot

**Comment by luancarvalhomartins** [comment]
Thank you very much and feel free to file a new issue should you need any further assistance!
