### ISSUE TITLE
error about gmx

### ISSUE THREAD

**Issue by zh2417** [luancarvalhomartins/PyAutoFEP#117]
I found the bash runall.sh nohup log with the following results:
tar: /water/md/rerun/.pkl: Cannot stat: No such file or directory
tar: /water/md/rerun/.xvg: Cannot stat: No such file or directory
tar: /water/md/rerun/.edr: Cannot stat: No such file or directory
tar: /protein/md/rerun/.pkl: Cannot stat: No such file or directory
tar: /protein/md/rerun/.xvg: Cannot stat: No such file or directory
tar: /protein/md/rerun/.edr: Cannot stat: No such file or directory
tar: /protein/md/lambda/lambda_pbcfit.xtc: Cannot stat: No such file or directory
tar: /protein/md/lambda/lambda.log: Cannot stat: No such file or directory
tar: /protein/md/lambda/lambda.edr: Cannot stat: No such file or directory
tar: /water/md/lambda/lambda.xtc: Cannot stat: No such file or directory
tar: /water/md/lambda/lambda.log: Cannot stat: No such file or directory
tar: /water/md/lambda/lambda.edr: Cannot stat: No such file or directory
tar: /protein/md/lambda/analysis.log: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
I find I only have command “gmx”， not gmx_mpi”. I also use tutorial01 and data from workdir. 
![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/72326396/b68640f1-319c-4b40-b126-a5874b24f20b)
![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/72326396/abc16dc9-834d-4e67-b724-d110b5ffa2e7)
what should I do to solve this issue？thank you very much.
I would like to ask if PyAutoFEP can only support the mpi version of gromacs (gmx_mpi), and gmx cannot run the project? As far as I know, the mpi version of gromacs is suitable for supercomputing platforms, and I am using a single machine, gmx_mpi may not perform well on the machine I use, is that true? So can I use PyAutoFEP using gmx or do I have to use gmx_mpi. Looking forward to your answer, I'm very sorry to trouble you and thank you for your work.

**Comment by luancarvalhomartins** [comment]
That is true, PyAutoFEP requires GROMACS to be compiled with MPI support, as it is required to use `gmx mdrun -multidir`. You will need to install or compile `gmx_mpi` to run FEP using PyAutoFEP. This is required for running in a single machine as well.

See https://manual.gromacs.org/current/user-guide/mdrun-features.html#running-multi-simulations for further info on this feature.
