### ISSUE TITLE
UnicodeDecodeErrorv when running prepare_dual_topology  

### ISSUE THREAD

**Issue by xrik** [luancarvalhomartins/PyAutoFEP#132]
Dear LUAN：
  I try to reproduce the tutorial, when I proceed to the step: prepare_dual_topology.py --config_file=step2.ini , it give follow error message:

_=============== mdp and run steps=================
         Complex                    Water          
        min01.mdp                 min01.mdp        
        min02.mdp                 min02.mdp        
        min03.mdp                  nve.mdp         
         nve.mdp                   nvt.mdp         
         nvt.mdp                   npt.mdp         
         npt.mdp                   md.mdp          
         md.mdp                       -            
==================================================
================= Input ligands ==================
   Name         Molecule            Topology      
  FXR_12   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(Cl)c1[H] lig_data/FXR_12.itp
  FXR_74   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(Br)c1[H] lig_data/FXR_74.itp
  FXR_76   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c([H])c1[H] lig_data/FXR_76.itp
  FXR_84   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(F)c1[H] lig_data/FXR_84.itp
  FXR_85   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(C([H])([H])[H])c1[H] lig_data/FXR_85.itp
  FXR_88   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(C(F)(F)F)c1[H] lig_data/FXR_88.itp
==================================================
================= Perturbations ==================
         State A                  State B         
         FXR_12                   FXR_74          
         FXR_12                   FXR_76          
         FXR_12                   FXR_84          
         FXR_12                   FXR_85          
         FXR_12                   FXR_88          
==================================================
=================== Poses read ===================
Name            File                 Details             
FXR_12          {'molecule': <rdkit.Chem.PropertyMol.PropertyMol object at 0x7fee34152520>, 'topology': ['lig_data/FXR_12.itp']}                   
=============== Superimposed poses ===============
Name            File                      Note           
FXR_12          {'molecule': <rdkit.Chem.PropertyMol.PropertyMol object at 0x7fee34152520>, 'topology': ['lig_data/FXR_12.itp']} Read from saved state
==================================================
================== Align poses ===================
Molecule FXR_12 aligned
================ Working on pairs ================
Perturbation Pose Coordinates
============ Working on FXR_12-FXR_74 ============
FXR_12→FXR_74
================ Building system =================
Traceback (most recent call last):
  File "/home/manager/Program/PyAutoFEP-master/prepare_dual_topology.py", line 4559, in <module>
    build_data = prepare_complex_system(
  File "/home/manager/Program/PyAutoFEP-master/os_util.py", line 558, in wrap_trace
    return f(*args, **kwargs)
  File "/home/manager/Program/PyAutoFEP-master/prepare_dual_topology.py", line 680, in prepare_complex_system
    copyfiles = build_posres_and_chain_itp(
  File "/home/manager/Program/PyAutoFEP-master/os_util.py", line 558, in wrap_trace
    return f(*args, **kwargs)
  File "/home/manager/Program/PyAutoFEP-master/prepare_dual_topology.py", line 389, in build_posres_and_chain_itp
    fix_chain_restraint(this_filename, index_posre_data[prot_group][0], verbosity=verbosity)
  File "/home/manager/Program/PyAutoFEP-master/prepare_dual_topology.py", line 174, in fix_chain_restraint
    restraint_data = os_util.read_file_to_buffer(restraint_file, die_on_error=True, return_as_list=True)
  File "/home/manager/Program/PyAutoFEP-master/os_util.py", line 104, in read_file_to_buffer
    data_buffer = input_file.readlines()
  File "/home/manager/anaconda3/envs/PyAutoFEP/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position **47**: invalid start byte_

it sometimes happens with position **45-46**  in the last line, sometime with position **48**, sometimes successful with Building system for FXR_12→FXR_74  ,but then get the error message with Building system for FXR_12→FXR_84. I have also succeed once and got the tutorial.bin file.
I am using ubuntu 18, conda environment, gromacs 2020.2, running in VMware, 4CPUs, 6G memory.  (I also delete all the PaxHeader subfolder, otherwise it causes error) 
I use default step2.ini setting except one line:  output_scripttype = bash
following is my running command:  
(PyAutoFEP) manager@ubuntu:~/Program/PyAutoFEP-master/docs/tutorial01/workdir$ python /home/manager/Program/PyAutoFEP-master/prepare_dual_topology.py --config_file=step2.ini

**Comment by xrik** [comment]
i added encoding='ISO-8859-1' in line 103 as   with open(filename, 'r', encoding='ISO-8859-1') as input_file:  to file os_util.py
and it returns following error message: 

=============== mdp and run steps=================
         Complex                    Water          
        min01.mdp                 min01.mdp        
        min02.mdp                 min02.mdp        
        min03.mdp                  nve.mdp         
         nve.mdp                   nvt.mdp         
         nvt.mdp                   npt.mdp         
         npt.mdp                   md.mdp          
         md.mdp                       -            
==================================================
================= Input ligands ==================
   Name         Molecule            Topology      
  FXR_12   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(Cl)c1[H] lig_data/FXR_12.itp
  FXR_74   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(Br)c1[H] lig_data/FXR_74.itp
  FXR_76   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c([H])c1[H] lig_data/FXR_76.itp
  FXR_84   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(F)c1[H] lig_data/FXR_84.itp
  FXR_85   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(C([H])([H])[H])c1[H] lig_data/FXR_85.itp
  FXR_88   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(C(F)(F)F)c1[H] lig_data/FXR_88.itp
==================================================
================= Perturbations ==================
         State A                  State B         
         FXR_12                   FXR_74          
         FXR_12                   FXR_76          
         FXR_12                   FXR_84          
         FXR_12                   FXR_85          
         FXR_12                   FXR_88          
==================================================
=================== Poses read ===================
Name            File                 Details             
FXR_12          {'molecule': <rdkit.Chem.PropertyMol.PropertyMol object at 0x7f59e072e160>, 'topology': ['lig_data/FXR_12.itp']}                   
=============== Superimposed poses ===============
Name            File                      Note           
FXR_12          {'molecule': <rdkit.Chem.PropertyMol.PropertyMol object at 0x7f59e072e160>, 'topology': ['lig_data/FXR_12.itp']} Read from saved state
==================================================
================== Align poses ===================
Molecule FXR_12 aligned
================ Working on pairs ================
Perturbation Pose Coordinates
============ Working on FXR_12-FXR_74 ============
FXR_12→FXR_74
================ Building system =================

=================== STACK INFO ===================
  File "/home/manager/Program/PyAutoFEP-master/prepare_dual_topology.py", line 4562, in <module>
    build_data = prepare_complex_system(
  File "/home/manager/Program/PyAutoFEP-master/os_util.py", line 560, in wrap_trace
    return f(*args, **kwargs)
  File "/home/manager/Program/PyAutoFEP-master/prepare_dual_topology.py", line 739, in prepare_complex_system
    os_util.local_print('Failed to run {} {}. Error code {}.\nCommand line was: {}\n\nstdout:\n{}\n\n'
  File "/home/manager/Program/PyAutoFEP-master/os_util.py", line 315, in local_print
    formatted_string = '\n{:=^50}\n{}{:=^50}\n'.format(' STACK INFO ', ''.join(traceback.format_stack()),
=================== STACK INFO ===================
[ERROR] Failed to run gmx grompp. Error code 1.
[ERROR] Command line was: ['gmx', 'grompp', '-f', '/tmp/tmpbw09es0u/tutorial\n\n\noutput_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/genion_step5_180141_21122023.mdp', '-c', '/tmp/tmpbw09es0u/tutorial\n\n\noutput_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolvated_step4_180141_21122023.gro', '-p', '/tmp/tmpbw09es0u/tutorial\n\n\noutput_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top', '-o', '/tmp/tmpbw09es0u/tutorial\n\n\noutput_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/genion_step6_180141_21122023.tpr', '-maxwarn', '1', '-po', '/tmp/tmpbw09es0u/tutorial\n\n\noutput_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/mdout_step6_180141_21122023.mdp']
[ERROR] 
[ERROR] stdout:
[ERROR] Analysing residue names:
[ERROR] There are:   236    Protein residues
[ERROR] There are:     1      Other residues
[ERROR] There are: 10203      Water residues
[ERROR] Analysing Protein...
[ERROR] Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
[ERROR] This run will generate roughly 3 Mb of data
[ERROR] 
[ERROR] 
[ERROR] stderr:
[ERROR]                       :-) GROMACS - gmx grompp, 2020.2 (-:
[ERROR] 
[ERROR]                             GROMACS is written by:
[ERROR]      Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
[ERROR]     Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd    
[ERROR]  Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray     
[ERROR]   Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang  
[ERROR]   Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
[ERROR]     Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson    
[ERROR]   Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund   
[ERROR]     Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall   
[ERROR]     Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov  
[ERROR]    Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen 
[ERROR]  Christian Wennberg    Maarten Wolf      Artem Zhmurov   
[ERROR]                            and the project leaders:
[ERROR]         Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel
[ERROR] 
[ERROR] Copyright (c) 1991-2000, University of Groningen, The Netherlands.
[ERROR] Copyright (c) 2001-2019, The GROMACS development team at
[ERROR] Uppsala University, Stockholm University and
[ERROR] the Royal Institute of Technology, Sweden.
[ERROR] check out http://www.gromacs.org for more information.
[ERROR] 
[ERROR] GROMACS is free software; you can redistribute it and/or modify it
[ERROR] under the terms of the GNU Lesser General Public License
[ERROR] as published by the Free Software Foundation; either version 2.1
[ERROR] of the License, or (at your option) any later version.
[ERROR] 
[ERROR] GROMACS:      gmx grompp, version 2020.2
[ERROR] Executable:   /usr/local/bin/gmx
[ERROR] Data prefix:  /usr/local
[ERROR] Working dir:  /home/manager/Program/PyAutoFEP-master/docs/tutorial01/workdir
[ERROR] Command line:
[ERROR]   gmx grompp -f '/tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/genion_step5_180141_21122023.mdp' -c '/tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolvated_step4_180141_21122023.gro' -p '/tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top' -o '/tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/genion_step6_180141_21122023.tpr' -maxwarn 1 -po '/tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/mdout_step6_180141_21122023.mdp'
[ERROR] 
[ERROR] 
[ERROR] NOTE 1 [file /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/genion_step5_180141_21122023.mdp]:
[ERROR]   For a correct single-point energy evaluation with nsteps = 0, use
[ERROR]   continuation = yes to avoid constraining the input coordinates.
[ERROR] 
[ERROR] Setting the LD random seed to -1085800848
[ERROR] 
[ERROR] WARNING 1 [file protein_step1_180141_21122023_Protein.itp, line 5]:
[ERROR]   Too few parameters on line (source file
[ERROR]   /home/manager/Program/gromacs-2020.2/src/gromacs/gmxpreprocess/toppush.cpp, line 342)
[ERROR] 
[ERROR] 
[ERROR] WARNING 2 [file protein_step1_180141_21122023_Protein.itp, line 22]:
[ERROR]   Too few parameters on line (source file
[ERROR]   /home/manager/Program/gromacs-2020.2/src/gromacs/gmxpreprocess/toppush.cpp, line 342)
[ERROR] 
[ERROR] 
[ERROR] WARNING 3 [file protein_step1_180141_21122023_Protein.itp, line 25]:
[ERROR]   Too few parameters on line (source file
[ERROR]   /home/manager/Program/gromacs-2020.2/src/gromacs/gmxpreprocess/toppush.cpp, line 342)
[ERROR] 
[ERROR] Generated 449826 of the 449826 non-bonded parameter combinations
[ERROR] Generating 1-4 interactions: fudge = 0.5
[ERROR] Generated 449826 of the 449826 1-4 parameter combinations
[ERROR] 
[ERROR] WARNING 4 [file protein_step1_180141_21122023_Protein2.itp, line 5]:
[ERROR]   Too few parameters on line (source file
[ERROR]   /home/manager/Program/gromacs-2020.2/src/gromacs/gmxpreprocess/toppush.cpp, line 1907)
[ERROR] 
[ERROR] 
[ERROR] WARNING 5 [file protein_step1_180141_21122023_Protein2.itp, line 22]:
[ERROR]   Too few parameters on line (source file
[ERROR]   /home/manager/Program/gromacs-2020.2/src/gromacs/gmxpreprocess/toppush.cpp, line 1907)
[ERROR] 
[ERROR] 
[ERROR] WARNING 6 [file protein_step1_180141_21122023_Protein2.itp, line 25]:
[ERROR]   Too few parameters on line (source file
[ERROR]   /home/manager/Program/gromacs-2020.2/src/gromacs/gmxpreprocess/toppush.cpp, line 1907)
[ERROR] 
[ERROR] Excluding 3 bonded neighbours molecule type 'Protein'
[ERROR] Excluding 3 bonded neighbours molecule type 'Protein2'
[ERROR] Excluding 3 bonded neighbours molecule type 'LIG'
[ERROR] Excluding 2 bonded neighbours molecule type 'SOL'
[ERROR] 
[ERROR] NOTE 2 [file systemsolv_step4_180141_21122023.top, line 66]:
[ERROR]   System has non-zero total charge: -10.000000
[ERROR]   Total charge should normally be an integer. See
[ERROR]   http://www.gromacs.org/Documentation/Floating_Point_Arithmetic
[ERROR]   for discussion on how close it should be to an integer.
[ERROR]   
[ERROR] 
[ERROR] 
[ERROR] Warning: atom name 3873 in /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top and /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolvated_step4_180141_21122023.gro does not match (O00_const_idx1 - O1)
[ERROR] Warning: atom name 3874 in /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top and /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolvated_step4_180141_21122023.gro does not match (C01_const_idx2 - C1)
[ERROR] Warning: atom name 3875 in /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top and /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolvated_step4_180141_21122023.gro does not match (O02_const_idx3 - O2)
[ERROR] Warning: atom name 3876 in /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top and /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolvated_step4_180141_21122023.gro does not match (C03_const_idx4 - C2)
[ERROR] Warning: atom name 3877 in /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top and /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolvated_step4_180141_21122023.gro does not match (C04_const_idx5 - C3)
[ERROR] Warning: atom name 3878 in /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top and /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolvated_step4_180141_21122023.gro does not match (C05_const_idx6 - C4)
[ERROR] Warning: atom name 3879 in /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top and /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolvated_step4_180141_21122023.gro does not match (C06_const_idx7 - C5)
[ERROR] Warning: atom name 3880 in /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top and /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolvated_step4_180141_21122023.gro does not match (C07_const_idx8 - C6)
[ERROR] Warning: atom name 3881 in /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top and /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolvated_step4_180141_21122023.gro does not match (N08_const_idx9 - N1)
[ERROR] Warning: atom name 3882 in /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top and /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolvated_step4_180141_21122023.gro does not match (C09_const_idx10 - C7)
[ERROR] Warning: atom name 3883 in /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top and /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolvated_step4_180141_21122023.gro does not match (O0A_const_idx11 - O3)
[ERROR] Warning: atom name 3884 in /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top and /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolvated_step4_180141_21122023.gro does not match (C0B_const_idx12 - C8)
[ERROR] Warning: atom name 3885 in /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top and /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolvated_step4_180141_21122023.gro does not match (C0C_const_idx13 - C9)
[ERROR] Warning: atom name 3886 in /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top and /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolvated_step4_180141_21122023.gro does not match (C0D_const_idx14 - C10)
[ERROR] Warning: atom name 3887 in /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top and /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolvated_step4_180141_21122023.gro does not match (N0E_const_idx15 - N2)
[ERROR] Warning: atom name 3888 in /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top and /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolvated_step4_180141_21122023.gro does not match (C0F_const_idx16 - C11)
[ERROR] Warning: atom name 3889 in /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top and /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolvated_step4_180141_21122023.gro does not match (C0G_const_idx17 - C12)
[ERROR] Warning: atom name 3890 in /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top and /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolvated_step4_180141_21122023.gro does not match (S0H_const_idx18 - S1)
[ERROR] Warning: atom name 3891 in /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top and /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolvated_step4_180141_21122023.gro does not match (O0I_const_idx19 - O4)
[ERROR] Warning: atom name 3892 in /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top and /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolvated_step4_180141_21122023.gro does not match (O0J_const_idx20 - O5)
[ERROR] (more than 20 non-matching atom names)
[ERROR] 
[ERROR] WARNING 7 [file systemsolv_step4_180141_21122023.top, line 66]:
[ERROR]   58 non-matching atom names
[ERROR]   atom names from /tmp/tmpbw09es0u/tutorial
[ERROR]   
[ERROR]   
[ERROR]   output_scripttype =
[ERROR]   bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top will be used
[ERROR]   atom names from /tmp/tmpbw09es0u/tutorial
[ERROR]   
[ERROR]   
[ERROR]   output_scripttype =
[ERROR]   bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolvated_step4_180141_21122023.gro will be ignored
[ERROR] 
[ERROR] 
[ERROR] Cleaning up constraints and constant bonded interactions with virtual sites
[ERROR] 
[ERROR] NOTE 3 [file systemsolv_step4_180141_21122023.top, line 66]:
[ERROR]   The bond in molecule-type Protein between atoms 78 OG1 and 79 HG1 has an
[ERROR]   estimated oscillational period of 9.0e-03 ps, which is less than 10 times
[ERROR]   the time step of 1.0e-03 ps.
[ERROR]   Maybe you forgot to change the constraints mdp option.
[ERROR] 
[ERROR] Number of degrees of freedom in T-Coupling group rest is 73005.00
[ERROR] 
[ERROR] NOTE 4 [file /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/genion_step5_180141_21122023.mdp]:
[ERROR]   NVE simulation with an initial temperature of zero: will use a Verlet
[ERROR]   buffer of 10%. Check your energy drift!
[ERROR] 
[ERROR] 
[ERROR] NOTE 5 [file /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/genion_step5_180141_21122023.mdp]:
[ERROR]   You are using a plain Coulomb cut-off, which might produce artifacts.
[ERROR]   You might want to consider using PME electrostatics.
[ERROR] 
[ERROR] 
[ERROR] 
[ERROR] There were 5 notes
[ERROR] 
[ERROR] There were 7 warnings
[ERROR] 
[ERROR] -------------------------------------------------------
[ERROR] Program:     gmx grompp, version 2020.2
[ERROR] Source file: src/gromacs/gmxpreprocess/grompp.cpp (line 2353)
[ERROR] 
[ERROR] Fatal error:
[ERROR] Too many warnings (7).
[ERROR] If you are sure all warnings are harmless, use the -maxwarn option.
[ERROR] 
[ERROR] For more information and tips for troubleshooting, please check the GROMACS
[ERROR] website at http://www.gromacs.org/Documentation/Errors
[ERROR] -------------------------------------------------------
[ERROR] 
[ERROR] 
[ERROR] ==================================================
[ERROR] This is likely caused by a failing to edit the intermediate topology file /tmp/tmpbw09es0u/tutorial
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = bash/FXR_12-FXR_74/protein/build_system_180141_21122023/systemsolv_step4_180141_21122023.top. Rerunning with output_hidden_temp_dir=False may solve this issue.

**Comment by wenzeyu126553** [comment]
I encountered a similar issue. How did you manage to resolve it?
