### ISSUE TITLE
solute_scaling_selection not accepting dictionaries as input

### ISSUE THREAD

**Issue by baba-hashimoto** [luancarvalhomartins/PyAutoFEP#15]
Now that the without rest2 calculation works, I am trying the with rest2 calculation.
https://www.plumed.org/doc-v2.7/user-doc/html/hrex.html　
I understand that Tools/rest2.sh is running to perform the task described in the link above.

Currently, I am getting the following error.
==================================================
[ERROR] Failed to read scaling selection file.
[ERROR] Could not read file LIG: O00_const_idx1 (and read_file_to_buffer wall called with die_on_error=False). Error was: [Errno 2] No such file or directory: 'LIG: O00_const_idx1'
=================== STACK INFO ===================
  File "../../prepare_dual_topology.py", line 2948, in <module>
    solute_scaling_atoms_dict = process_scaling_input(arguments.solute_scaling_selection)
  File "../../prepare_dual_topology.py", line 2160, in process_scaling_input
    '', verbosity=verbosity)
  File "/work113/**/PyAutoFEP/os_util.py", line 99, in read_file_to_buffer
    local_print(error_message, msg_verbosity=verbosity_level.error, current_verbosity=verbosity)
  File "/work113/**/PyAutoFEP/os_util.py", line 292, in local_print
    formatted_string += '\n{:=^50}\n{}{:=^50}'.format(' STACK INFO ', ''.join(traceback.format_stack()),
=================== STACK INFO ===================

As far as the program is concerned, it fails to write solute_scaling_slection. If you could give me an example of how to fill it out, that would be helpful.

**Comment by librahoo** [comment]
It seemed like solute_scaling_selection points to a file, within the file just write
```
LIG:C
LIG:N
LIG:O
LIG:Cl
LIG:Br
```
should work, the ligand heavy atoms could be scaled as marked as REST2 scaled atom in the SystemFull.top, however, all the opls atomtypes are also scaled without REST2 mark, I wondered wether this top file should work for REST2 jobs.

**Comment by luancarvalhomartins** [comment]
`solute_scaling_selection` expects a dictionary or file with a dictionary describing which atoms should be subject to solute scaling. The keys are the moleculetypes to operate on and the values are the atoms to match. There are two ways of matching atoms. First, by providing a list is integers, so that atoms with that index (in the topology) will be scaled. Alternatively, a regex can be used, so that atoms names matching that regex will de affected. Example:

```
LIG: .+           // Match all atoms of the ligand
```

**Comment by baba-hashimoto** [comment]
I used the following input.
# This is the configuration section for prepare_dual_topology.py (which is the only section in this file, but the [ section ] is mandatory)
[prepare_dual_topology]

# Read ligands and topologies from this folder
input_ligands = lig_data

# Read the macromolecule structure from this file
structure = receptor_data/5q17_processed.pdb

# This is the force field directory, it will be copied to each perturbation dir and used to prepare the MD systems
extradirs = oplsaam.ff

# Options controlling the core-constrained superimposition
# First select the use of it instead of reading all ligand poses
pose_loader = superimpose

# Use this pose as the reference for the superimposition
poses_reference_pose_superimpose = receptor_data/9mv.pdb

# Name of the output. This will be a self-extracting bash file
perturbations_dir = /work113/tmp/PyAutoFEP/docs/tutorial01_plumed/tutorial

# Sets the path to GROMACS executable in the run node, uncomment and modify if needed.
# gmx_bin_run = /usr/local/bin/gromacs

# Options controlling the output, see manual for more info. Uncomment as needed
# FEP legs are to be submitted to a slurm scheduler
output_scripttype = pbs
# Run these commands at the beginnig of the jog (useful to load modules, importing libs)
#output_runbefore = module load python3; module load cuda
# Fine-tune job resources
output_resources = all_nodes:1; all_cpus:10; all_gpus:1
# Use a python file instead of a binary during the collect step
output_collecttype = python
#REST2
solute_scaling_bin = rest2
hrex = 500
solute_scaling_selection = LIG: .+
solute_scaling = 0.5

However, I got the following error.
==================================================
[ERROR] Failed to read scaling selection file.
[ERROR] Could not read file LIG: .+ (and read_file_to_buffer wall called with die_on_error=False). Error was: [Errno 2] No such file or directory: 'LIG: .+'
=================== STACK INFO ===================
  File "../../prepare_dual_topology.py", line 2948, in <module>
    solute_scaling_atoms_dict = process_scaling_input(arguments.solute_scaling_selection)
  File "../../prepare_dual_topology.py", line 2160, in process_scaling_input
    '', verbosity=verbosity)
  File "/work113/tbaba/PyAutoFEP/os_util.py", line 99, in read_file_to_buffer
    local_print(error_message, msg_verbosity=verbosity_level.error, current_verbosity=verbosity)
  File "/work113/tmp/PyAutoFEP/os_util.py", line 292, in local_print
    formatted_string += '\n{:=^50}\n{}{:=^50}'.format(' STACK INFO ', ''.join(traceback.format_stack()),
=================== STACK INFO ===================

Is there something wrong with the usage? I would appreciate your comments.

**Comment by luancarvalhomartins** [comment]
Sorry, you are right. `solute_scaling_selection` is not reading the input as a dict as it should. That's indeed a bug. I'm fixing it promptly.

**Comment by luancarvalhomartins** [comment]
Commit a379d9613bebdc849b57ddf0c110cd83faadc14f fixes this issue. Closing.

**Comment by baba-hashimoto** [comment]
Thanks for your help.
