### ISSUE TITLE
Bump the alchemlyb to 0.6.0

### ISSUE THREAD

**Issue by xiki-tempula** [luancarvalhomartins/PyAutoFEP#24]
With the new release, the issue (https://github.com/choderalab/pymbar/issues/419) is resolved by the more robust MBAR solver, which could be called as

`from alchemlyb.estimators import AutoMBAR as MBAR`

**Comment by luancarvalhomartins** [comment]
Absolutely agreed. I was also following that bug ([#](https://github.com/choderalab/pymbar/issues/419)) and saw the commit. Hope the improved solver also brings better results for difficult cases. I am fixing it ASAP.
