### ISSUE TITLE
suggested check routine for analyze_results.py

### ISSUE THREAD

**Issue by insukjoung** [luancarvalhomartins/PyAutoFEP#25]
https://github.com/luancarvalhomartins/PyAutoFEP/blob/fcc52e914fac9edebc1675dd032421915a2986f4/analyze_results.py#L1460-L1462
 
After the last line above, it would be better check if `xvg_directory` is in valid status like:
```python
            xvg_directory = os.path.join(data_dir, each_entry, system, 'md', 'rerun')
            if not os.path.isdir(xvg_directory) or len(glob(os.path.join(xvg_directory,'*.xvg'))) == 0:
                continue
```
In case the directory is not a directory or xvg files are not found, it can be skipped. The first case occurs if you run analyze_results.py without packing the output directory,. The `runall*.sh` files in the leg directory give errors without the modification above.

**Comment by luancarvalhomartins** [comment]
This has been reported before (#12) and I wrote a patch for that issue, but somehow I forgot to commit. I am feeling a bit dumb here.
