### ISSUE TITLE
The problem i met of generate_perturbation_map.py

### ISSUE THREAD

**Issue by jgxs** [luancarvalhomartins/PyAutoFEP#3]
Hi! I read your journal named *PyAutoFEP: An Automated Free Energy Perturbation Workflow for GROMACS Integrating Enhanced Sampling Methods*, which is such a great work.

I try to do some FEP calculations in your method while i met some problems.
I used the smis.smi(see below) as input of the generate_perturbation_map.py with command line.
```sh
python generate_perturbation_map.py --input smis.smi
``` 
the smis.smi is:
```
CN1C(=NC2(CC(C)(C)Oc3ccc(cc23)c4cccc(Cl)c4)C1=O)N aname
CN1C(=NC2(CC(C)(C)Oc3cnc(cc23)c4cccc(Cl)c4)C1=O)N bname
CN1C(=NC2(CC(C)(C)Oc3ncc(cc23)c4cccc(Cl)c4)C1=O)N cname
CN1C(=NC2(CC(C)(C)Oc3ccc(cc23)c4cccc(I)c4)C1=O)N dname
CN1C(=NC2(CC(C)(C)Oc3ccc(cc23)c4cccc(Br)c4)C1=O)N ename
```
However, i met a TypeError of :
```
Traceback (most recent call last):
  File "generate_perturbation_map.py", line 497, in <module>
    custom_mcs=custom_user_data, savestate=progress_data, verbosity=arguments.verbose)
  File "generate_perturbation_map.py", line 138, in fill_thermograph
    for (edge_i, edge_j) in thermograph.edges:
TypeError: 'method' object is not iterable
```
Did I use that in a wrong way? 
Thank you for your help.

**Comment by luancarvalhomartins** [comment]
Hi. Thank you for reporting.

Which is your networkx version? This error suggests you are using a 1.X version, while PyAutoFEP requires 2.X. On networkx 2.X, G.edges returns an EdgeView [1]. Would you mind double checking that?

Thank you!

[1] https://networkx.org/documentation/stable/release/migration_guide_from_1.x_to_2.0.html

**Comment by jgxs** [comment]
Thanks for your help. It does work. It seems that the networkx installed by pip covered the correct version installed by conda in my env. 
Thanks a lot.
