### ISSUE TITLE
Can't read reference pose 9mv.pdb

### ISSUE THREAD

**Issue by GsGithub17** [luancarvalhomartins/PyAutoFEP#32]
Hi, I was able to generate the perturbation map, however, the topology preparation is giving me error. 
It says failed to read pose data.  Please, I need your help in this regard. Thanks! 

```
PyAutoFEP]$ python prepare_dual_topology.py --config_file=step2.ini
=============== mdp and run steps=================
         Complex                    Water          
        min01.mdp                 min01.mdp        
        min02.mdp                 min02.mdp        
        min03.mdp                  nve.mdp         
         nve.mdp                   nvt.mdp         
         nvt.mdp                   npt.mdp         
         npt.mdp                   md.mdp          
         md.mdp                       -            
==================================================
================= Input ligands ==================
   Name         Molecule            Topology      
  FXR_12   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(Cl)c1[H] docs/tutorial01/workdir/lig_data/FXR_12.itp
  FXR_74   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(Br)c1[H] docs/tutorial01/workdir/lig_data/FXR_74.itp
  FXR_76   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c([H])c1[H] docs/tutorial01/workdir/lig_data/FXR_76.itp
  FXR_84   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(F)c1[H] docs/tutorial01/workdir/lig_data/FXR_84.itp
  FXR_85   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(C([H])([H])[H])c1[H] docs/tutorial01/workdir/lig_data/FXR_85.itp
  FXR_88   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(C(F)(F)F)c1[H] docs/tutorial01/workdir/lig_data/FXR_88.itp
==================================================
=================== Poses read ===================
Name            File                
[ERROR] Failed to read pose data from docs/tutorial01/workdir/receptor_data/9mv.pdb
[ERROR] 
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = slurm
[ERROR] output_collecttype = python with type .pdb
[ERROR] 
[ERROR] 
[ERROR] 
[ERROR] output_scripttype = slurm
[ERROR] output_collecttype = python
=================== STACK INFO ===================
  File "prepare_dual_topology.py", line 3250, in <module>
    verbosity=arguments.verbose, **arguments.poses_advanced_options)
  File "prepare_dual_topology.py", line 1324, in align_ligands
    save_state=save_state, verbosity=verbosity, **kwargs)
  File "/home/PyAutoFEP/docking_readers/superimpose_loader.py", line 80, in superimpose_poses
    verbosity=verbosity)['reference']
  File "/home/PyAutoFEP/docking_readers/generic_loader.py", line 60, in extract_docking_poses
    docking_mol_rd = generic_mol_read(ligand_format, each_mol['molecule'], verbosity=verbosity)
  File "/home/PyAutoFEP/docking_readers/generic_loader.py", line 209, in generic_mol_read
    msg_verbosity=os_util.verbosity_level.error, current_verbosity=verbosity)
  File "/home/PyAutoFEP/os_util.py", line 292, in local_print
    formatted_string += '\n{:=^50}\n{}{:=^50}'.format(' STACK INFO ', ''.join(traceback.format_stack()),
=================== STACK INFO ===================
```
(I formatted the output as inline code, this greatly improves readability - @luancarvalhomartins)

**Comment by luancarvalhomartins** [comment]
Closing as it seems the problem was indeed the config file.

**Comment by GsGithub17** [comment]
Hi Luan,

Just a quick question, can I run the batch jobs in parallel or they should
be run serial one by one (one after the other)?

#!/bin/bashlastjid=()lastjid+=( $(sbatch --parsable
FXR_12-FXR_74/runall_FXR_12-FXR_74_water.sh) )lastjid+=( $(sbatch --parsable
FXR_12-FXR_74/runall_FXR_12-FXR_74_protein.sh) )lastjid+=( $(sbatch
--parsable FXR_12-FXR_76/runall_FXR_12-FXR_76_water.sh) )lastjid+=( $(sbatch
--parsable FXR_12-FXR_76/runall_FXR_12-FXR_76_protein.sh) )lastjid+=( $(sbatch
--parsable FXR_12-FXR_84/runall_FXR_12-FXR_84_water.sh) )lastjid+=( $(sbatch
--parsable FXR_12-FXR_84/runall_FXR_12-FXR_84_protein.sh) )lastjid+=( $(sbatch
--parsable FXR_12-FXR_85/runall_FXR_12-FXR_85_water.sh) )lastjid+=( $(sbatch
--parsable FXR_12-FXR_85/runall_FXR_12-FXR_85_protein.sh) )lastjid+=( $(sbatch
--parsable FXR_12-FXR_88/runall_FXR_12-FXR_88_water.sh) )lastjid+=( $(sbatch
--parsable FXR_12-FXR_88/runall_FXR_12-FXR_88_protein.sh) )sbatch
--parsable --dependency=afterok:$(IFS=,;
echo "${lastjid[*]}") pack.sh


PS: I was able to complete the PyAutoFEP tutorial.
    See attached figure. The plots do not necessarily match but I was able
to complete the tutorial with quite numerous issues along the way.
Thank you!

Best regards,

Gemechis

------------------------------------------
Gemechis Degaga (Ph.D.)
Postdoctoral Research Associate
Michigan Technological University
Department of Physics
1400 Townsend DR--49931
Houghton Michigan
USA
Tel: +1 906 281 8149

**Comment by luancarvalhomartins** [comment]
Yes, jobs can be run in parallel using a job scheduler (see option `output_scripttype` in `prepare_dual_topology.py`). Running multiple jobs with no job scheduler is not currently supported. I guess it would be possible to run jobs in parallel using eg, GNU parallel, but at the same time, doing so efficiently in a single node is super tricky. If you really want to do that, you can write a script or use parallel to execute all of `*_*/runall_*-*_{water,protein}.sh` scripts. If you are running in multiple nodes, a job scheduler is likely what you need.

Glad to know you was able to complete the tutorial. Sorry to hear that you had issues. I hope I am able to polish the tutorial to prevent this annoyances.

Due to stochastic nature of MD, the results are not identical, but the trend should be captured by FEP.

**Comment by GsGithub17** [comment]
Yes, I have a SLURM workload manager.

If I want to run the jobs of the sbatch lines in the runall.sh file in
parallel, what should I need to change?

I mean, in the following, it sounds like lastjid is being used to run the
sbatch jobs in serial? The question is, would it be okay if I run them at
the same time?

#!/bin/bashlastjid=()lastjid+=( $(sbatch --parsable
FXR_12-FXR_74/runall_FXR_12-FXR_74_water.sh) )lastjid+=( $(sbatch --parsable
FXR_12-FXR_74/runall_FXR_12-FXR_74_protein.sh) )lastjid+=( $(sbatch
--parsable FXR_12-FXR_76/runall_FXR_12-FXR_76_water.sh) )lastjid+=( $(sbatch
--parsable FXR_12-FXR_76/runall_FXR_12-FXR_76_protein.sh) )lastjid+=( $(sbatch
--parsable FXR_12-FXR_84/runall_FXR_12-FXR_84_water.sh) )lastjid+=( $(sbatch
--parsable FXR_12-FXR_84/runall_FXR_12-FXR_84_protein.sh) )lastjid+=( $(sbatch
--parsable FXR_12-FXR_85/runall_FXR_12-FXR_85_water.sh) )lastjid+=( $(sbatch
--parsable FXR_12-FXR_85/runall_FXR_12-FXR_85_protein.sh) )lastjid+=( $(sbatch
--parsable FXR_12-FXR_88/runall_FXR_12-FXR_88_water.sh) )lastjid+=( $(sbatch
--parsable FXR_12-FXR_88/runall_FXR_12-FXR_88_protein.sh) )sbatch
--parsable --dependency=afterok:$(IFS=,;
echo "${lastjid[*]}") pack.sh

Best,

Gemechis

------------------------------------------
Gemechis Degaga (Ph.D.)
Postdoctoral Research Associate
Michigan Technological University
Department of Physics
1400 Townsend DR--49931
Houghton Michigan
USA
Tel: +1 906 281 8149

**Comment by luancarvalhomartins** [comment]
In this case, running in parallel depends solely on SLURM and you don't have to change a thing. The script will submit all jobs to the queue, only the `pack.sh` job depends on the others. If the jobs are not being run in parallel, take a look at your SLURM queue and resources.

_Rationale of the script_: `sbatch --parsable` submits a job to the manager and returns the job id as an integer. `lastjid` stores the job id, which will be used in the depend clause of the pack job. The submission via `sbatch` runs serially, but the jobs itself can run in parallel.

**Comment by GsGithub17** [comment]
THANK YOU SO MUCH!

That is what I wanted to know!

Best,

Gemechis
------------------------------------------
Gemechis Degaga (Ph.D.)
Postdoctoral Research Associate
Michigan Technological University
Department of Physics
1400 Townsend DR--49931
Houghton Michigan
USA
Tel: +1 906 281 8149

**Comment by GsGithub17** [comment]
Just an update. The pose fixe went alright. But now the alignment part is
giving a similar error. See below.
I need a quick suggestion to dig more in.

================== Align poses ===================
Traceback (most recent call last):
  File "prepare_dual_topology.py", line 3250, in <module>
    verbosity=arguments.verbose, **arguments.poses_advanced_options)
  File "prepare_dual_topology.py", line 1361, in align_ligands
    ligand_mol = mol_util.obmol_to_rwmol(each_ligand, verbosity=verbosity)
  File "/home/gemechis/PyAutoFEP00/mol_util.py", line 205, in obmol_to_rwmol
    ignoreSmoothingFailures=True)
RuntimeError: Pre-condition Violation
getNumImplicitHs() called without preceding call to calcImplicitValence()
Violation occurred on line 297 in file Code/GraphMol/Atom.cpp
Failed Expression: d_implicitValence > -1
RDKIT: 2022.03.1
BOOST: 1_74



Thank you!
------------------------------------------
Gemechis Degaga (Ph.D.)
Postdoctoral Research Associate
Michigan Technological University
Department of Physics
1400 Townsend DR--49931
Houghton Michigan
USA
Tel: +1 906 281 8149

**Comment by luancarvalhomartins** [comment]
Ok, what you really need is #38 to be fixed. I will try to do that this afternoon.

In the mean time, you _may_ get code to work by adding a call to `rdmol.UpdatePropertyCache()` to mol_utils line 202 (right after `rdmol = rdedmol.GetMol()`)

**Comment by GsGithub17** [comment]
Hi Luan,

I really got excited and start reproducing figure 5 (top left) for the 14
FXR compounds. I decided to use the FXR_10 as the base.

I was able to generate the perturbation map. But this time the dual
topology generation seems not to work well.

I you can give a quick guide on how to resolve this, it would be great

Here is the error message that came on pose reading

-----

=================== Poses read ===================
Name            File
Traceback (most recent call last):
  File "prepare_dual_topology.py", line 3250, in <module>
    verbosity=arguments.verbose, **arguments.poses_advanced_options)
  File "prepare_dual_topology.py", line 1324, in align_ligands
    save_state=save_state, verbosity=verbosity, **kwargs)
  File "/home/gemechis/PyAutoFEP15/docking_readers/superimpose_loader.py",
line 80, in superimpose_poses
    verbosity=verbosity)['reference']
  File "/home/gemechis/PyAutoFEP15/docking_readers/generic_loader.py", line
60, in extract_docking_poses
    docking_mol_rd = generic_mol_read(ligand_format, each_mol['molecule'],
verbosity=verbosity)
  File "/home/gemechis/PyAutoFEP15/docking_readers/generic_loader.py", line
204, in generic_mol_read
    docking_mol_rd = mol_util.obmol_to_rwmol(ob_molecule)
  File "/home/gemechis/PyAutoFEP15/mol_util.py", line 205, in obmol_to_rwmol
    ignoreSmoothingFailures=True)
RuntimeError: Pre-condition Violation
getNumImplicitHs() called without preceding call to calcImplicitValence()
Violation occurred on line 297 in file Code/GraphMol/Atom.cpp
Failed Expression: d_implicitValence > -1
RDKIT: 2022.03.1
BOOST: 1_74

------------------------------------------------

Thank you!

Gemechis

------------------------------------------
Gemechis Degaga (Ph.D.)
Postdoctoral Research Associate
Michigan Technological University
Department of Physics
1400 Townsend DR--49931
Houghton Michigan
USA
Tel: +1 906 281 8149
