### ISSUE TITLE
RuntimeError: Sequence modified during iteration

### ISSUE THREAD

**Issue by yingioi0** [luancarvalhomartins/PyAutoFEP#33]
While I am processing the step below followed by tutorial:
$prepare_dual_topology.py --config_file=step2.ini
I got this error message:
=============== Superimposed poses ===============
Name            File                      Note           
Traceback (most recent call last):
  File "/home/ying/2t/PyAutoFEP-master/prepare_dual_topology.py", line 3245, in <module>
    poses_mol_data = align_ligands(receptor_structure_mol, poses_input,
  File "/home/ying/2t/PyAutoFEP-master/prepare_dual_topology.py", line 1323, in align_ligands
    docking_mol_local = superimpose_poses(superimpose_loader_ligands, reference_pose_superimpose,
  File "/home/ying/2t/PyAutoFEP-master/docking_readers/superimpose_loader.py", line 124, in superimpose_poses
    thismol = merge_topologies.constrained_embed_shapeselect(each_ligand_mol, rdkit_reference_pose,
  File "/home/ying/2t/PyAutoFEP-master/merge_topologies.py", line 360, in constrained_embed_shapeselect
    [molecule.RemoveConformer(conformer.GetId()) for conformer in molecule.GetConformers()
  File "/home/ying/2t/PyAutoFEP-master/merge_topologies.py", line 360, in <listcomp>
    [molecule.RemoveConformer(conformer.GetId()) for conformer in molecule.GetConformers()
RuntimeError: Sequence modified during iteration

I'm sure rdkit and openbabel has been installed, only one point is that I changed 'import pybel' to 'from openbabel import pybel' in all the python scripts, how can I fix it? May you help me, thanks.

**Comment by yingioi0** [comment]
By the way I did not change any other files given by tutorial.

**Comment by luancarvalhomartins** [comment]
This is odd and I have no idea why this would happen. From RDKit docs, GetConformers should return a (static?) sequence.

```
GetConformers((Mol)arg1) → _ROConformerSeq:
Returns a read-only sequence containing all of the molecule’s Conformers.
```

Anyway, I added a changing making sure a copy of the list is used instead of a ref to the list. By the way, which rdkit version are you using?

**Comment by luancarvalhomartins** [comment]
Would you mind checking if this commit solves the issue?

**Comment by yingioi0** [comment]
Thank you! It works now. my version of RDKit is 2021.09.5, is it too old? And there is another error occur in the same step, prepare_dual_topology:
================== Align poses ===================
Traceback (most recent call last):
  File "/home/ying/2t/PyAutoFEP-master/prepare_dual_topology.py", line 3250, in <module>
    verbosity=arguments.verbose, **arguments.poses_advanced_options)
  File "/home/ying/2t/PyAutoFEP-master/prepare_dual_topology.py", line 1361, in align_ligands
    ligand_mol = mol_util.obmol_to_rwmol(each_ligand, verbosity=verbosity)
  File "/home/ying/2t/PyAutoFEP-master/mol_util.py", line 205, in obmol_to_rwmol
    ignoreSmoothingFailures=True)
RuntimeError: Pre-condition Violation
	getNumImplicitHs() called without preceding call to calcImplicitValence()
	Violation occurred on line 183 in file Code/GraphMol/Atom.cpp
	Failed Expression: d_implicitValence > -1
	RDKIT: 2021.09.5
	BOOST: 1_74

I have searched this and here are some advice( I'm not a programmer anyway ):
https://github.com/rdkit/rdkit/issues/3708
https://github.com/rdkit/rdkit/issues/805
https://github.com/rdkit/rdkit/issues/2450
This maybe a long way to make it perfect.
& I'm a Chinese so there exist a time gap. If I have any language problem, please tell me then I can change it thanks.

**Comment by luancarvalhomartins** [comment]
Glad to know that the first issue was solved. RDKit 2021.09.5 should work fine. I will try to test this that version and try to find what's going on.

Regarding your second issue, it is likely because some group of the input molecule is not being correctly converted from/to OBMol. It is likely a bug, but it is very hard to trace without the actual inputs. Would you mind sharing your molecules? If you would rather not do so publicly, fell free to reach me by email (luancarvalhomartins@gmail.com). In case you agree sending the structures, I will not share/show/disclose it with anyone.

(In case you would rather not share the molecules at all, let me know so I can try reworking the ligand alignment to avoid the problematic OBMol<->RWMol conversions)

Thank you very much.

**Comment by luancarvalhomartins** [comment]
Ok, I am guessing you would rather not share your molecules at all, which is totally OK. I am trying to solve this by avoiding using openbabel translate and rotate, so I am opening another bug report to track this specific issue and closing this one.

Again, feel free to reach me in case you need any help.

**Comment by luancarvalhomartins** [comment]
Please, follow the converting issue at #38
