### ISSUE TITLE
module 'pybel' has no attribute 'ob'

### ISSUE THREAD

**Issue by GsGithub17** [luancarvalhomartins/PyAutoFEP#34]
This error showed up suddenly, any reason and solution to this would be greatly appreciated.  

PyAutoFEP]$ python prepare_dual_topology.py --config_file step2.ini 
Traceback (most recent call last):
  File "/home/gdegaga_championsoncology_com/PyAutoFEP/prepare_dual_topology.py", line 2952, in <module>
    pybel.ob.obErrorLog.SetOutputLevel(pybel.ob.obError)
AttributeError: module 'pybel' has no attribute 'ob'

Thanks!

**Comment by yingioi0** [comment]
please change 'import pybel' to 'from openbabel import pybel' in all the python scripts. (I'm a user only not author,but it works)
By the way, can you run 'prepare_dual_topology.py' scripts smoothly? I think I have met problem on running it.

**Comment by GsGithub17** [comment]
Thanks for your suggestion, I will definitely try that. 

'prepare_dual_topology.py initially was giving me a bunch of issues. But some of the issues were resolved just by removing indentation in the config file step2.ini file on the variable lines.

I'm still trying to run this smoothly. I'll let you know how things go.

**Comment by GsGithub17** [comment]
@yingioi0 

After trying your suggestion, this is what I got. 

 File "prepare_dual_topology.py", line 30, in <module>
    from openbabel import pybel
ImportError: cannot import name 'pybel' from 'openbabel'

**Comment by luancarvalhomartins** [comment]
Thank you for your message.

All of this seems to be a openbabel version issue. `pybel` was removed in openbabel 3 (which is currently unsupported by PyAutoFEP). The fact that you cannot do `from openbabel import pybel` suggests you are not using openbabel 3. Would you mind checking your version (so I can try to reproduce your exact issue). If you have openbabel 3, unfortunately, you'll have to downgrade to openbabel 2 for now.

Bumping support to OB 3 (and maybe removing OB 2 support) is on the roadmap, but not something I will be able to to right now.

**Comment by luancarvalhomartins** [comment]
I just realized something. There is another pybel (https://github.com/pybel/pybel). Any chance you have it installed and you are importing another module?

**Comment by GsGithub17** [comment]
Thank you! 
I was able to resolve this problem by installing OB 2.

But I have now a new problem related to GROMACS. 

I'm just putting the error here for now, but will open an actual new issue once I completely understand what the problem is. 
But have any suggestion mean time, I greatly appreciate it. 

Below is the error message. 


[ERROR] 
[ERROR] Setting the LD random seed to -1868213161
[ERROR] Generated 7750 of the 7750 non-bonded parameter combinations
[ERROR] Generating 1-4 interactions: fudge = 0.5
[ERROR] Generated 7750 of the 7750 1-4 parameter combinations
[ERROR] Excluding 3 bonded neighbours molecule type 'Protein'
[ERROR] Excluding 3 bonded neighbours molecule type 'Protein2'
[ERROR] Excluding 2 bonded neighbours molecule type 'SOL'
[ERROR] Excluding 2 bonded neighbours molecule type 'SOL'
[ERROR] Excluding 3 bonded neighbours molecule type 'LIG'
[ERROR] 
[ERROR] NOTE 3 [file systemsolv_step4_141653_23032022.top, line 58]:
[ERROR]   System has non-zero total charge: -11.000000
[ERROR]   Total charge should normally be an integer. See
[ERROR]   http://www.gromacs.org/Documentation/Floating_Point_Arithmetic
[ERROR]   for discussion on how close it should be to an integer.
[ERROR]   
[ERROR] 
[ERROR] 
[ERROR] 
[ERROR] -------------------------------------------------------
[ERROR] Program:     gmx grompp, version 2018.8
[ERROR] Source file: src/gromacs/gmxpreprocess/grompp.cpp (line 619)
[ERROR] 
[ERROR] Fatal error:
[ERROR] number of coordinates in coordinate file
[ERROR] (/tmp/tmpxw7wm48l/tutorial/FXR_12-FXR_74/protein/build_system_141653_23032022/systemsolvated_step4_141653_23032022.gro,
[ERROR] 39884)
[ERROR]              does not match topology
[ERROR] (/tmp/tmpxw7wm48l/tutorial/FXR_12-FXR_74/protein/build_system_141653_23032022/systemsolv_step4_141653_23032022.top,
[ERROR] 4184)
[ERROR] 
[ERROR] For more information and tips for troubleshooting, please check the GROMACS
[ERROR] website at http://www.gromacs.org/Documentation/Errors
[ERROR] -------------------------------------------------------
[ERROR] 
[ERROR] 
[ERROR] ==================================================
[ERROR] This is likely caused by a failing to edit the intermediate topology file /tmp/tmpxw7wm48l/tutorial/FXR_12-FXR_74/protein/build_system_141653_23032022/systemsolv_step4_141653_23032022.top. Rerunning with output_hidden_temp_dir=False may solve this issue.
=================== STACK INFO ===================
  File "prepare_dual_topology.py", line 3548, in <module>
    verbosity=arguments.verbose)
  File "prepare_dual_topology.py", line 495, in prepare_complex_system
    msg_verbosity=os_util.verbosity_level.error, current_verbosity=verbosity)
  File "/home/gdegaga_championsoncology_com/PyAutoFEP/os_util.py", line 292, in local_print
    formatted_string += '\n{:=^50}\n{}{:=^50}'.format(' STACK INFO ', ''.join(traceback.format_stack()),
=================== STACK INFO ===================

**Comment by GsGithub17** [comment]
> Thank you! I was able to resolve this problem by installing OB 2.
> 
> But I have now a new problem related to GROMACS.
> 
> I'm just putting the error here for now, but will open an actual new issue once I completely understand what the problem is. But have any suggestion mean time, I greatly appreciate it.
> 
> Below is the error message.
> 
> [ERROR] [ERROR] Setting the LD random seed to -1868213161 [ERROR] Generated 7750 of the 7750 non-bonded parameter combinations [ERROR] Generating 1-4 interactions: fudge = 0.5 [ERROR] Generated 7750 of the 7750 1-4 parameter combinations [ERROR] Excluding 3 bonded neighbours molecule type 'Protein' [ERROR] Excluding 3 bonded neighbours molecule type 'Protein2' [ERROR] Excluding 2 bonded neighbours molecule type 'SOL' [ERROR] Excluding 2 bonded neighbours molecule type 'SOL' [ERROR] Excluding 3 bonded neighbours molecule type 'LIG' [ERROR] [ERROR] NOTE 3 [file systemsolv_step4_141653_23032022.top, line 58]: [ERROR] System has non-zero total charge: -11.000000 [ERROR] Total charge should normally be an integer. See [ERROR] http://www.gromacs.org/Documentation/Floating_Point_Arithmetic [ERROR] for discussion on how close it should be to an integer. [ERROR] [ERROR] [ERROR] [ERROR] [ERROR] ------------------------------------------------------- [ERROR] Program: gmx grompp, version 2018.8 [ERROR] Source file: src/gromacs/gmxpreprocess/grompp.cpp (line 619) [ERROR] [ERROR] Fatal error: [ERROR] number of coordinates in coordinate file [ERROR] (/tmp/tmpxw7wm48l/tutorial/FXR_12-FXR_74/protein/build_system_141653_23032022/systemsolvated_step4_141653_23032022.gro, [ERROR] 39884) [ERROR] does not match topology [ERROR] (/tmp/tmpxw7wm48l/tutorial/FXR_12-FXR_74/protein/build_system_141653_23032022/systemsolv_step4_141653_23032022.top, [ERROR] 4184) [ERROR] [ERROR] For more information and tips for troubleshooting, please check the GROMACS [ERROR] website at http://www.gromacs.org/Documentation/Errors [ERROR] ------------------------------------------------------- [ERROR] [ERROR] [ERROR] ================================================== [ERROR] This is likely caused by a failing to edit the intermediate topology file /tmp/tmpxw7wm48l/tutorial/FXR_12-FXR_74/protein/build_system_141653_23032022/systemsolv_step4_141653_23032022.top. Rerunning with output_hidden_temp_dir=False may solve this issue. =================== STACK INFO =================== File "prepare_dual_topology.py", line 3548, in verbosity=arguments.verbose) File "prepare_dual_topology.py", line 495, in prepare_complex_system msg_verbosity=os_util.verbosity_level.error, current_verbosity=verbosity) File "/home/gdegaga_championsoncology_com/PyAutoFEP/os_util.py", line 292, in local_print formatted_string += '\n{:=^50}\n{}{:=^50}'.format(' STACK INFO ', ''.join(traceback.format_stack()), =================== STACK INFO ===================
