### ISSUE TITLE
Energy unit formatting

### ISSUE THREAD

**Issue by Benstime** [luancarvalhomartins/PyAutoFEP#39]
1. The output energy value is divided by beta twice in analyze_results.py
142:  beta = 1 / (formatted_energy_units[units].kB * temperature)
242:  this_ddg = -1 * estimator_obj.delta_f_[0].iloc[-1] / beta
1718: value1 = '{:0.1f}\u00B1{:0.1f} {}'.format(system_a['ddg'] / beta, system_a['error'] / beta,formatted_energy_units[arguments.units].text)
===================================================
2. If I choose the kBT unit, the beta is 1/temperature, but the unit of the mbar estimator_obj delta_f_ is already kT.
why output ddg = delta_f_/(1/temperature) = delta_f_*temperature

**Comment by luancarvalhomartins** [comment]
It seems you are correct. Thank you very much for filling this bug. When using `units = "kBT"`, the energy is wrongly outputed in ddG*T, as `beta` should be simply 1. This bug won't affect results in kcal/mol or kJ/mol.

Again, sorry for the mistake. I'm fixing it RN.

**Comment by Benstime** [comment]
Another problem is that the  plot_ddg_vs_lambda1 function in analyze_results.py 
 680: y = [each_value / formatted_energy_units[units].kB for each_value in values]
 681: ye = [each_value / formatted_energy_units[units].kB for each_value in error]

I think "each_value" unit is kT, which come from estimator of mbar. 
But I plot_ddg_vs_lambda1 image, 
the value of y in the unit of kJ/mol is smaller than kcal/mol: 
  y[kJ/mol] < y[kcal/mol] 
since formatted_energy_units[kJ/mol].kB > formatted_energy_units[kcal/mol].kB,
which is not quite right.
