### ISSUE TITLE
Error with Multi-Simulation

### ISSUE THREAD

**Issue by GsGithub17** [luancarvalhomartins/PyAutoFEP#40]
Hi all, 

while running  this 

<sbatch --parsable  FXR_12-FXR_74/runall_FXR_12-FXR_74_protein.sh>

the following error showed up, anyone come-across this error before or any suggestion?

Thank you! 

GROMACS:      gmx mdrun, version 2021.5
Executable:   /home/easybuild/.local/easybuild/software/GROMACS/2021.5-foss-2021b-CUDA-11.4.1/bin/gmx_mpi
Data prefix:  /home/easybuild/.local/easybuild/software/GROMACS/2021.5-foss-2021b-CUDA-11.4.1
Working dir:  /home/gdegaga_championsoncology_com/PyAutoFEP/Slurmtest/tutorial/slurm00/FXR_12-FXR_74/protein/md
Command line:
  gmx_mpi mdrun -v --deffnm lambda -cpi lambda.cpt -multidir lambda0 lambda1 lambda2 lambda3 lambda4 lambda5 lambda6 lambda7 lambda8 lambda9 lambda10 lambda11

-------------------------------------------------------
Program:     gmx mdrun, version 2021.5

-------------------------------------------------------
Program:     gmx mdrun, version 2021.5
Source file: src/gromacs/mdrunutility/handlerestart.cpp (line 575)
Function:    void gmx::{anonymous}::StartingBehaviorHandler::ensureMultiSimBehaviorsMatch(const gmx_multisim_t*)
MPI rank:    1 (out of 12)

Inconsistency in user input:

Multi-simulations must all start in the same way, either a new
simulation, a restart with appending, or a restart without appending.
However, the contents of the multi-simulation directories you specified
were inconsistent with each other. Either remove the checkpoint file
from each directory, or ensure each directory has a checkpoint file from

**Comment by GsGithub17** [comment]
This is has been resolved, and this issue can be closed.
Thank you!

**Comment by luancarvalhomartins** [comment]
Glad to know that you solved the issue. Would you mind sharing a bit about what happened and how you manage to solve it? It could help others and help me improve the code. If you rather not to, that's fine.

Thank you.
