### ISSUE TITLE
“pose_loader = generic” can't get normal results as expected

### ISSUE THREAD

**Issue by chengbao917** [luancarvalhomartins/PyAutoFEP#46]
Dear Prof.

We set the following parameters:
"pose_loader = generic
poses_reference_structure = protein.pdb
prepare_dual_topology.py --poses_input $generic_poses --poses_input $generic_poses --config_file=input.ini"

The command works fine, but the results of pairs' overlap as if generic had not been added. It seems like "pose_loader = generic" isn't working.

We will appreciate your kindly advise.

Thanks,
Bao

**Comment by luancarvalhomartins** [comment]
Sorry for the late reply, I have been sick for some days. I am taking a look into it tomorrow morning.

**Comment by luancarvalhomartins** [comment]
Thank you very much for you bug report. I will need a bit more info to tackle it.

First, I am not quite sure what you meant by "results of pairs' overlap as if generic had not been added". Are the dual-molecule poses different from the input poses of the correspondingly A state? If yes, how so? What is the input poses filetype and the structure of `$generic_poses`? Also, would you mind attaching the `prepare_dual_topology.py` output with debug verbosity (`-vvvv`)?

**Comment by chengbao917** [comment]
> Thank you very much for you bug report. I will need a bit more info to tackle it.
> 
> First, I am not quite sure what you meant by "results of pairs' overlap as if generic had not been added". Are the dual-molecule poses different from the input poses of the correspondingly A state? If yes, how so? What is the input poses filetype and the structure of `$generic_poses`? Also, would you mind attaching the `prepare_dual_topology.py` output with debug verbosity (`-vvvv`)?

Sorry for the late reply,  yes, the dual-molecule poses were different from the input poses of the correspondingly A state. The input pose filetype was .mol2 and the structure of $generic_poses was .pdb.

# This is the configuration section for prepare_dual_topology.py (which is the only section in this file, but the [ section ] is mandatory)
[prepare_dual_topology]

# Read ligands and topologies from this folder
input_ligands = ligtop

# Read the macromolecule structure from this file
structure = protein.pdb
poses_input = {'ligand_1': 'ligand_1.pdb',
                'ligand_2': 'ligand_2.pdb',
                'ligand_5': 'ligand_5.pdb'}

poses_reference_structure = protein.pdb

# This is the force field directory, it will be copied to each perturbation dir and used to prepare the MD systems
extradirs = /home/program/gromacs2021.4/share/gromacs/top/amber03.ff

# Options controlling the core-constrained superimposition
# First select the use of it instead of reading all ligand poses
pose_loader='generic'

# Use this pose as the reference for the superimposition
#poses_reference_pose_superimpose = ligand_crystal.pdb

# Name of the output. This will be a self-extracting bash file
perturbations_dir = workspace

# Sets the path to GROMACS executable in the run node, uncomment and modify if needed.
# gmx_bin_run = /usr/local/bin/gromacs

# Options controlling the output, see manual for more info. Uncomment as needed
# FEP legs are to be submitted to a slurm scheduler
output_scripttype = slurm
# Run these commands at the beginnig of the jog (useful to load modules, importing libs)
# output_runbefore = module load python3; module load cuda
# Fine-tune job resources
output_resources = all_cpus:$ncpus; all_gpus:1; all_time:24; all_mem:50000;
# Use a python file instead of a binary during the collect step
#output_collecttype = python

**Comment by luancarvalhomartins** [comment]
Your config file seems fine. Files `ligand_1.pdb`, `ligand_2.pdb`, and `ligand_5.pdb` should have been used as source of positions for the state A. Would you mind attaching the output of `prepare_dual_topology.py` using `-vvvv`? Also, in case you are allowed to do so, the actual input poses and resulting protein systems would help a lot (in case you would rather not post publicly here, feel free to send me by email at luancarvalhomartins@gmail.com).

Note: you do not need to pass the FF directory if it is in the GROMACS data path, as amber03.ff should be. See manual for how to select a FF on such case.

**Comment by chengbao917** [comment]
> 

Thanks for your kind reply. And, I'll try your suggestion.  

I'd like to consult you on something else. The reasonable generation of the perturbation mapping is the premise and key for FEP calculation. Sometimes we need to check whether the mapping of each pair is reasonable. Whether PyAutoFEP can check and view the mapping result of the pairs, and edit it after completing the mapping. 
 
Looking forward to your reply.
Thanks

**Comment by luancarvalhomartins** [comment]
Sorry, for some reason I completely forget do reply to this message. The perturbation map can be inspected as a SVG image generated by `generate_perturbation_map.py`. Unfortunately, there is no convenient way to edit it, other then manually editing the text version of the perturbation map.

I am currently working on a GUI that will greatly simplify working with the perturbation maps, but it is in early codeing stages.

**Comment by luancarvalhomartins** [comment]
I believe that the original bug report was fixed by https://github.com/luancarvalhomartins/PyAutoFEP/commit/c6e427c318c695f5d4a5d0f375e17b0bb16ced68.
