### ISSUE TITLE
Using "mcs_custom _mcs" results in "Molecule does not match the core" when using SMARTS with defined bond orders

### ISSUE THREAD

**Issue by chengbao917** [luancarvalhomartins/PyAutoFEP#47]
```
================ Working on pairs ================
Perturbation Pose Coordinates
========== Working on ligand_1-ligand_2 ==========
[ERROR] Embeding of molecule ligand_2 (SMILES = [H]c1c(F)c(F)c(F)c([H])c1C([H])([H])n1c(=O)n(C([H])([H])C(=O)N([H])C([H])([H])[H])c(=O)n([H])/c1=N\c1c(C([H])([H])[H])c([H])c2nc(C([H])([H])[H])sc2c1[H]) to common core [10*]~c1~c~c~c~c~c~1~N~c1~n~c(~O)~n~c(~O)~n~1~C~c1~c~c(~F)~c(~F)~c(~F)~c~1~[11*] with molecule ligand_1 (SMILES = [H]c1c([H])c(OC([H])([H])[H])c([H])c([H])c1/N=c1\n([H])c(=O)n(C([H])([H])c2nc([H])n(C([H])([H])[H])n2)c(=O)n1C([H])([H])c1c([H])c(F)c(F)c(F)c1[H]) has failed. Molecule does not match the core.
```
 
We set up mcs_custom_mcs, and we made sure that SMARTS was the common core between Pairs. But we always get an error.  We set the structure of the core to be a little bit larger.

We will appreciate your kindly advise.
Thanks,
Bao.

---
2022.05.27: I formatted the output for better reading (@luancarvalhomartins)

**Comment by luancarvalhomartins** [comment]
Sorry for the late reply, I have been sick for some days. I am taking a look into it tomorrow morning.

**Comment by luancarvalhomartins** [comment]
The core you provided using `mcs_custom_mcs` indeed doesn't seem to match the SMILES using both RDKit or SMARTS.plus. Note that (A) all atoms of the core must match atoms of the ligands; (B) the matching must be continuous; (C) the algorithm start using a strict matching, falling back to looser options automatically. From the SMARTS.plus output, it is clear that there are non-matching atoms.

![image](https://user-images.githubusercontent.com/29309798/170783610-1fcfc254-aa64-43e2-88a1-07f39fb31896.png)

I also tested generating input molecules using your SMILES:
```
# Generate mol files from SMILES
cd input_ligs
obabel -:"[H]c1c([H])c(OC([H])([H])[H])c([H])c([H])c1/N=c1\n([H])c(=O)n(C([H])([H])c2nc([H])n(C([H])([H])[H])n2)c(=O)n1C([H])([H])c1c([H])c(F)c(F)c(F)c1[H]" -Oligand_1.mol --gen3d
obabel -:"[H]c1c(F)c(F)c(F)c([H])c1C([H])([H])n1c(=O)n(C([H])([H])C(=O)N([H])C([H])([H])[H])c(=O)n([H])/c1=N\c1c(C([H])([H])[H])c([H])c2nc(C([H])([H])[H])sc2c1[H]" -Oligand_2.mol --gen3d
cd ..

# Dock the ligs to a dummy receptor 
cd poses
parallel 'obabel {} -O{/.}.pdbqt' ::: ../input_ligs/*
parallel --jobs=1 '$HOME/software/qvina2/qvina2.1 --config vina_input.txt --ligand {}' ::: lig*.pdbqt
cd ..

# Run prepare_dual_topology.py
python3 $HOME/Dropbox/Scripts/PyAutoFEP/prepare_dual_topology.py --config_file config.ini --mcs_custom_mcs="[10*]c1ccccc1Nc1nc(O)nc(O)n1Cc1c~c(~F)~c(~F)~c(F)c1[11*]"
```
And I was able to reproduce your issue:
```
==================================================
================ Working on pairs ================
Perturbation Pose Coordinates
========== Working on ligand_1-ligand_2 ==========
[ERROR] Could not find a match between molecule [H]c1c([H])c(OC([H])([H])[H])c([H])c([H])c1/N=c1\n([H])c(=O)n(C([H])([H])c2nc([H])n(C([H])([H])[H])n2)c(=O)n1C([H])([H])c1c([H])c(F)c(F)c(F)c1[H] and MCS SMARTS [H]~[#6]1~[#6]~[#6]~[#6]~[#6]~[#6]~1~[#6]~[#7]1~[#6]~[#7](~[#6]~[10#0])~[#6](~[11#0])~[#7](~[H])~[#6]~1~[#7]~[#6]1~[#6](~[12#0])~[#6](~[H])~[#6]2~[#7]~[14#0]~[#16]~[#6]~2~[#6]~1~[H] using extra-relaxed matching. Cannot continue. Check your input files. 
```

Not passing `mcs_custom_mcs` (ie, allowing `prepare_dual_topology.py` calculating MCS between the ligs) works. I also tried the passing the following SMARTS to `mcs_custom_mcs`:
SMARTS | Works? | Comment
--|--|--
`[#8]~[#6]~1~[#7]~[#6](~[#8])~[#7](~[#6]~[#6]~2~[#6]~[#6](~F)~[#6](~F)~[#6](~F)~[#6]~2)~[#6](~[#7]~[#6]~2~[#6]~[#6]~[#6]~[#6]~[#6]~2)~[#7]~1` | No | I think the ring bonded to N doesn't match, leading to the error.
`[#7]~[#6]~1~[#7]~[#6](~[#8])~[#7]~[#6](~[#8])~[#7]~1~[#6]~[#6]~1~[#6]~[#6](~F)~[#6](~F)~[#6](~F)~[#6]~1` | Yes | The ring connected to the N was removed
`[#6]~[#7]~1~[#6](~[#8])~[#7]~[#6](~[#7])~[#7](~[#6]~[#6]~2~[#6]~[#6](~F)~[#6](~F)~[#6](~F)~[#6]~2)~[#6]~1~[#8]` | Yes | A CH2 also matches between the ligs
`Cn1c(=O)[nH]\c(=N/c2ccccc2)n(Cc2cc(F)c(F)c(F)c2)c1=O` | No | When setting the bond orders, the custom MCS fails. I am not sure if it's related to the aromaticity of the cyanuric-like ring, but it didn't work. That's the MCS I extracted using the PyAutoFEP `prepare_dual_topology.py`.

`mcs_custom_mcs` seems to work, but the atom matching code is certainly somewhat quirky. Unfortunately, most of this part of the code is just a series of calls to RDKit functions. Should you have more problems, let me know so we can try to figure things out together. Something that may help you is using different custom MCS for certain pairs, in case they are more problematic.

**Comment by chengbao917** [comment]
Porf. sorry for the late reply. Thank you for your detailed explanation.  I want to know these two SMARTS how to converted.  I think the molecule core need converts by RDKit functions with no bond order.

**Comment by chengbao917** [comment]
These two SMARTS: '[#7]~[#6]~1~[#7]~[#6](~[#8])~[#7]~[#6](~[#8])~[#7]~1~[#6]~[#6]~1~[#6]~[#6](~F)~[#6](~F)~[#6](~F)~[#6]~1',  '[#6]~[#7]~1~[#6](~[#8])~[#7]~[#6](~[#7])~[#7](~[#6]~[#6]~2~[#6]~[#6](~F)~[#6](~F)~[#6](~F)~[#6]~2)~[#6]~1~[#8]'

**Comment by luancarvalhomartins** [comment]
I didn't quite get it. Do you mean how to edit a SMARTS removing its bond orders? I did that using MarvinSketch, but I think multiple tools are able to do such. In MarvinSketch you can select something, click the bond tool, then select a bond type. It will be applied to all selected bond.

In case you would like to know why the core SMARTS with bond orders didn't work, I don't know either. It is something worth investigating, but I won't be able to do that in the next few days.

**Comment by chengbao917** [comment]
> I didn't quite get it. Do you mean how to edit a SMARTS removing its bond orders? I did that using MarvinSketch, but I think multiple tools are able to do such. In MarvinSketch you can select something, click the bond tool, then select a bond type. It will be applied to all selected bond.
> 
> In case you would like to know why the core SMARTS with bond orders didn't work, I don't know either. It is something worth investigating, but I won't be able to do that in the next f
