### ISSUE TITLE
prepare_dual_topology.py fails with Gromacs 2020 in the "Farnesoid X receptor tutorial"

### ISSUE THREAD

**Issue by yx0516** [luancarvalhomartins/PyAutoFEP#51]
When i run the tutorial step by step and got the following error. We would appreciate it if you could check with the tutorial with Gromacs 2020 when you have time.

[ERROR] Failed to run gmx grompp. Error code 1.
[ERROR] Command line was: ['gmx', 'grompp', '-f', '/tmp/tmpmxflrejy/tutorial/FXR_12-FXR_74/protein/build_system_160215_08062022/genion_step5_160215_08062022.mdp', '-c', '/tmp/tmpmxflrejy/tutorial/FXR_12-FXR_74/protein/build_system_160215_08062022/systemsolvated_step4_160215_08062022.gro', '-p', '/tmp/tmpmxflrejy/tutorial/FXR_12-FXR_74/protein/build_system_160215_08062022/systemsolv_step4_160215_08062022.top', '-o', '/tmp/tmpmxflrejy/tutorial/FXR_12-FXR_74/protein/build_system_160215_08062022/genion_step6_160215_08062022.tpr', '-maxwarn', '1', '-po', '/tmp/tmpmxflrejy/tutorial/FXR_12-FXR_74/protein/build_system_160215_08062022/mdout_step6_160215_08062022.mdp']
[ERROR] 
[ERROR] stdout:
[ERROR] 
[ERROR] 
[ERROR] stderr:
[ERROR]                       :-) GROMACS - gmx grompp, 2020.6 (-:
[ERROR] 
[ERROR]                             GROMACS is written by:
[ERROR]      Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
[ERROR]     Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd    
[ERROR]  Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray     
[ERROR]   Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang  
[ERROR]   Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
[ERROR]     Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson    
[ERROR]   Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund   
[ERROR]     Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall   
[ERROR]     Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov  
[ERROR]    Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen 
[ERROR]  Christian Wennberg    Maarten Wolf      Artem Zhmurov   
[ERROR]                            and the project leaders:
[ERROR]         Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel
[ERROR] 
[ERROR] Copyright (c) 1991-2000, University of Groningen, The Netherlands.
[ERROR] Copyright (c) 2001-2019, The GROMACS development team at
[ERROR] Uppsala University, Stockholm University and
[ERROR] the Royal Institute of Technology, Sweden.
[ERROR] check out http://www.gromacs.org for more information.
[ERROR] 
[ERROR] GROMACS is free software; you can redistribute it and/or modify it
[ERROR] under the terms of the GNU Lesser General Public License
[ERROR] as published by the Free Software Foundation; either version 2.1
[ERROR] of the License, or (at your option) any later version.
[ERROR] 
[ERROR] GROMACS:      gmx grompp, version 2020.6
[ERROR] Executable:   /data/software/gmx2020.6/bin/gmx
[ERROR] Data prefix:  /data/software/gmx2020.6
[ERROR] Working dir:  /data/user/yanx/workdir/repo/PyAutoFEP
[ERROR] Command line:
[ERROR]   gmx grompp -f /tmp/tmpmxflrejy/tutorial/FXR_12-FXR_74/protein/build_system_160215_08062022/genion_step5_160215_08062022.mdp -c /tmp/tmpmxflrejy/tutorial/FXR_12-FXR_74/protein/build_system_160215_08062022/systemsolvated_step4_160215_08062022.gro -p /tmp/tmpmxflrejy/tutorial/FXR_12-FXR_74/protein/build_system_160215_08062022/systemsolv_step4_160215_08062022.top -o /tmp/tmpmxflrejy/tutorial/FXR_12-FXR_74/protein/build_system_160215_08062022/genion_step6_160215_08062022.tpr -maxwarn 1 -po /tmp/tmpmxflrejy/tutorial/FXR_12-FXR_74/protein/build_system_160215_08062022/mdout_step6_160215_08062022.mdp
[ERROR] 
[ERROR] 
[ERROR] NOTE 1 [file /tmp/tmpmxflrejy/tutorial/FXR_12-FXR_74/protein/build_system_160215_08062022/genion_step5_160215_08062022.mdp]:
[ERROR]   For a correct single-point energy evaluation with nsteps = 0, use
[ERROR]   continuation = yes to avoid constraining the input coordinates.
[ERROR] 
[ERROR] Setting the LD random seed to -44077602
[ERROR] Generated 449826 of the 449826 non-bonded parameter combinations
[ERROR] Generating 1-4 interactions: fudge = 0.5
[ERROR] Generated 449826 of the 449826 1-4 parameter combinations
[ERROR] Excluding 3 bonded neighbours molecule type 'Protein'
[ERROR] Excluding 3 bonded neighbours molecule type 'Protein2'
[ERROR] Excluding 3 bonded neighbours molecule type 'LIG'
[ERROR] 
[ERROR] NOTE 2 [file systemsolv_step4_160215_08062022.top, line 56]:
[ERROR]   System has non-zero total charge: -10.000000
[ERROR]   Total charge should normally be an integer. See
[ERROR]   http://www.gromacs.org/Documentation/Floating_Point_Arithmetic
[ERROR]   for discussion on how close it should be to an integer.
[ERROR]   
[ERROR] 
[ERROR] 
[ERROR] 
[ERROR] -------------------------------------------------------
[ERROR] Program:     gmx grompp, version 2020.6
[ERROR] Source file: src/gromacs/gmxpreprocess/grompp.cpp (line 669)
[ERROR] 
[ERROR] Fatal error:
[ERROR] number of coordinates in coordinate file
[ERROR] (/tmp/tmpmxflrejy/tutorial/FXR_12-FXR_74/protein/build_system_160215_08062022/systemsolvated_step4_160215_08062022.gro,
[ERROR] 44742)
[ERROR]              does not match topology
[ERROR] (/tmp/tmpmxflrejy/tutorial/FXR_12-FXR_74/protein/build_system_160215_08062022/systemsolv_step4_160215_08062022.top,
[ERROR] 3930)
[ERROR] 
[ERROR] For more information and tips for troubleshooting, please check the GROMACS
[ERROR] website at http://www.gromacs.org/Documentation/Errors
[ERROR] -------------------------------------------------------
[ERROR] 
[ERROR] 
[ERROR] ==================================================
[ERROR] This is likely caused by a failing to edit the intermediate topology file /tmp/tmpmxflrejy/tutorial/FXR_12-FXR_74/protein/build_system_160215_08062022/systemsolv_step4_160215_08062022.top. Rerunning with output_hidden_temp_dir=False may solve this issue.
=================== STACK INFO ===================
  File "prepare_dual_topology.py", line 3547, in <module>
    verbosity=arguments.verbose)
  File "prepare_dual_topology.py", line 494, in prepare_complex_system
    msg_verbosity=os_util.verbosity_level.error, current_verbosity=verbosity)
  File "/data/user/yanx/workdir/repo/PyAutoFEP/os_util.py", line 292, in local_print
    formatted_string += '\n{:=^50}\n{}{:=^50}'.format(' STACK INFO ', ''.join(traceback.format_stack()),
=================== STACK INFO =================== @luancarvalhomartins

**Comment by luancarvalhomartins** [comment]
This hardly because of GROMACS version. From the error message:
**This is likely caused by a failing to edit the intermediate topology file /tmp/tmpmxflrejy/tutorial/FXR_12-FXR_74/protein/build_system_160215_08062022/systemsolv_step4_160215_08062022.top. Rerunning with output_hidden_temp_dir=False may solve this issue.**
Some systems use a tmpfs that somehow buffers IO so that editting of topologies fails (see #6). Please, retry with `output_hidden_temp_dir=False`. In case it still fails, please let me know.

**Comment by yx0516** [comment]
When i try the option output_hidden_temp_dir=False, it works!
Thanks a lot!

**Comment by luancarvalhomartins** [comment]
You are very welcomed. Thank you for using PyAutoFEP.
