### ISSUE TITLE
"Bad input file" error in tutorial

### ISSUE THREAD

**Issue by LuisFOrta** [luancarvalhomartins/PyAutoFEP#53]
I´m stuck in the "Farnesoid X receptor tutorial" step in which the perturbation map is generated. I keep getting the following error:

Traceback (most recent call last):
  File ".\PyAutoFEP\generate_perturbation_map.py", line 433, in <module>
    each_mol = mol_util.generic_mol_read(ligand_data=each_file, ligand_format=file_ext,
  File ".\PyAutoFEP\mol_util.py", line 1211, in generic_mol_read
    read_mol_data = rdkit.Chem.MolFromMolFile(ligand_data, removeHs=False)
OSError: Bad input file lig_data/*.mol

It seems that there's a problem with reading the files, so I also tried with simpler molecules and the mol2 file format, unfortunately getting the same "Bad input file" error. 

I´m running the following command in a Conda environment:

python .\PyAutoFEP\generate_perturbation_map.py --map_type=star --map_bias=FXR_12 --input lig_data/*.mol

The Conda environment has installed the following packages:

python                        3.9.12
rdkit                            2022.03.3
networkx                     2.8
alchemlyb                   0.6.0
pymbar                       3.0.5
openbabel                  3.1.1 
matplotlib                   3.5.1
numpy                        1.22.3

If anybody has any idea of how to fix this error, please let me know

**Comment by luancarvalhomartins** [comment]
It seems your shell did not expand `lig_data/*.mol`, hence the `OSError: Bad input file lig_data/*.mol`. You may want to double check that the files are there and that your shell is sane. BTW, you wrote `.\PyAutoFEP\generate_perturbation_map.py`. What OS are you using?

**Comment by LuisFOrta** [comment]
I´m using Windows as OS. About the shell not expanding lig_data/*.mol, does it mean that the shell is not correctly accessing the path to the file?

**Comment by luancarvalhomartins** [comment]
No, it means that the Windows shell doesn't understand the wildcard in `lig_data/*.mol` (see,for eg, https://superuser.com/questions/460598/is-there-any-way-to-get-the-windows-cmd-shell-to-expand-wildcard-paths). Try passing all filenames explicitly.

Just to let you know that PyAutoFEP was not tested on Windows (at least, by me). It may or may not work. I suggest you trying Windows Subsystem for Linux or a virtual machine in case it fails
