### ISSUE TITLE
gmx_mpi only use 20 threads(total 40  threads）and one GPU(total two GPUs) on my workstation, how can let the gmx_mpi use all threads and GPUs？

### ISSUE THREAD

**Issue by aixintiankong** [luancarvalhomartins/PyAutoFEP#57]

**Comment by luancarvalhomartins** [comment]
I guess you already found the solution, hope you did and that PyAutoFEP works great for you. Anyway, I am replying here for future reference.

`gmx` and `gmx_mpi` should be able to detect your node geometry and efficiently use it. In any case, you can set environment variables `OMP_NUM_THREADS` and `GMX_GPU_ID` using `--output_runbefore` option to tell GROMACS what to use. But be careful when doing so! GROMACS often detects things correctly, so make sure that everything is fine with your hardware and configuration.
