### ISSUE TITLE
environment: rerun/rerun_struct_coord.out: No such file or directory

### ISSUE THREAD

**Issue by luancarvalhomartins** [luancarvalhomartins/PyAutoFEP#59]
Hi. I still encountered **environment: rerun/rerun_struct_coord.out: No such file or directory** errors.
My perturbation_dir is /program/fep/workdir/**fep**, and I get the unk_matrix.pkl file in rerun/
[unk_matrix.zip](https://github.com/luancarvalhomartins/PyAutoFEP/files/9186962/unk_matrix.zip)

cadd@huiyu:~/program/fep/workdir/fep/drg_1-drg_2/protein/md/rerun$ ls

`lambda0.xvg                 rerun_struct11_coord8.edr  rerun_struct3_coord9.edr   rerun_struct7_coord0.edr
lambda10.xvg                rerun_struct11_coord8.log  rerun_struct3_coord9.log   rerun_struct7_coord0.log
lambda11.xvg                rerun_struct11_coord8.out  rerun_struct3_coord9.out   rerun_struct7_coord0.out
lambda1.xvg                 rerun_struct11_coord8.xvg  rerun_struct3_coord9.xvg   rerun_struct7_coord0.xvg
lambda2.xvg                 rerun_struct11_coord9.edr  rerun_struct4_coord0.edr   rerun_struct7_coord10.edr
lambda3.xvg                 rerun_struct11_coord9.log  rerun_struct4_coord0.log   rerun_struct7_coord10.log
lambda4.xvg                 rerun_struct11_coord9.out  rerun_struct4_coord0.out   rerun_struct7_coord10.out
lambda5.xvg                 rerun_struct11_coord9.xvg  rerun_struct4_coord0.xvg   rerun_struct7_coord10.xvg
lambda6.xvg                 rerun_struct1_coord0.edr   rerun_struct4_coord10.edr  rerun_struct7_coord11.edr
lambda7.xvg                 rerun_struct1_coord0.log   rerun_struct4_coord10.log  rerun_struct7_coord11.log
lambda8.xvg                 rerun_struct1_coord0.out   rerun_struct4_coord10.out  rerun_struct7_coord11.out
lambda9.xvg                 rerun_struct1_coord0.xvg   rerun_struct4_coord10.xvg  rerun_struct7_coord11.xvg
rerun_struct0_coord0.edr    rerun_struct1_coord10.edr  rerun_struct4_coord11.edr  rerun_struct7_coord1.edr
rerun_struct0_coord0.log    rerun_struct1_coord10.log  rerun_struct4_coord11.log  rerun_struct7_coord1.log
rerun_struct0_coord0.out    rerun_struct1_coord10.out  rerun_struct4_coord11.out  rerun_struct7_coord1.out
rerun_struct0_coord0.xvg    rerun_struct1_coord10.xvg  rerun_struct4_coord11.xvg  rerun_struct7_coord1.xvg
rerun_struct0_coord10.edr   rerun_struct1_coord11.edr  rerun_struct4_coord1.edr   rerun_struct7_coord2.edr
rerun_struct0_coord10.log   rerun_struct1_coord11.log  rerun_struct4_coord1.log   rerun_struct7_coord2.log
rerun_struct0_coord10.out   rerun_struct1_coord11.out  rerun_struct4_coord1.out   rerun_struct7_coord2.out
rerun_struct0_coord10.xvg   rerun_struct1_coord11.xvg  rerun_struct4_coord1.xvg   rerun_struct7_coord2.xvg
rerun_struct0_coord11.edr   rerun_struct1_coord1.edr   rerun_struct4_coord2.edr   rerun_struct7_coord3.edr
rerun_struct0_coord11.log   rerun_struct1_coord1.log   rerun_struct4_coord2.log   rerun_struct7_coord3.log
rerun_struct0_coord11.out   rerun_struct1_coord1.out   rerun_struct4_coord2.out   rerun_struct7_coord3.out
rerun_struct0_coord11.xvg   rerun_struct1_coord1.xvg   rerun_struct4_coord2.xvg   rerun_struct7_coord3.xvg
rerun_struct0_coord1.edr    rerun_struct1_coord2.edr   rerun_struct4_coord3.edr   rerun_struct7_coord4.edr
rerun_struct0_coord1.log    rerun_struct1_coord2.log   rerun_struct4_coord3.log   rerun_struct7_coord4.log
rerun_struct0_coord1.out    rerun_struct1_coord2.out   rerun_struct4_coord3.out   rerun_struct7_coord4.out
rerun_struct0_coord1.xvg    rerun_struct1_coord2.xvg   rerun_struct4_coord3.xvg   rerun_struct7_coord4.xvg
rerun_struct0_coord2.edr    rerun_struct1_coord3.edr   rerun_struct4_coord4.edr   rerun_struct7_coord5.edr
rerun_struct0_coord2.log    rerun_struct1_coord3.log   rerun_struct4_coord4.log   rerun_struct7_coord5.log
rerun_struct0_coord2.out    rerun_struct1_coord3.out   rerun_struct4_coord4.out   rerun_struct7_coord5.out
rerun_struct0_coord2.xvg    rerun_struct1_coord3.xvg   rerun_struct4_coord4.xvg   rerun_struct7_coord5.xvg
rerun_struct0_coord3.edr    rerun_struct1_coord4.edr   rerun_struct4_coord5.edr   rerun_struct7_coord6.edr
rerun_struct0_coord3.log    rerun_struct1_coord4.log   rerun_struct4_coord5.log   rerun_struct7_coord6.log
rerun_struct0_coord3.out    rerun_struct1_coord4.out   rerun_struct4_coord5.out   rerun_struct7_coord6.out
rerun_struct0_coord3.xvg    rerun_struct1_coord4.xvg   rerun_struct4_coord5.xvg   rerun_struct7_coord6.xvg
rerun_struct0_coord4.edr    rerun_struct1_coord5.edr   rerun_struct4_coord6.edr   rerun_struct7_coord7.edr
rerun_struct0_coord4.log    rerun_struct1_coord5.log   rerun_struct4_coord6.log   rerun_struct7_coord7.log
rerun_struct0_coord4.out    rerun_struct1_coord5.out   rerun_struct4_coord6.out   rerun_struct7_coord7.out
rerun_struct0_coord4.xvg    rerun_struct1_coord5.xvg   rerun_struct4_coord6.xvg   rerun_struct7_coord7.xvg
rerun_struct0_coord5.edr    rerun_struct1_coord6.edr   rerun_struct4_coord7.edr   rerun_struct7_coord8.edr
rerun_struct0_coord5.log    rerun_struct1_coord6.log   rerun_struct4_coord7.log   rerun_struct7_coord8.log
rerun_struct0_coord5.out    rerun_struct1_coord6.out   rerun_struct4_coord7.out   rerun_struct7_coord8.out
rerun_struct0_coord5.xvg    rerun_struct1_coord6.xvg   rerun_struct4_coord7.xvg   rerun_struct7_coord8.xvg
rerun_struct0_coord6.edr    rerun_struct1_coord7.edr   rerun_struct4_coord8.edr   rerun_struct7_coord9.edr
rerun_struct0_coord6.log    rerun_struct1_coord7.log   rerun_struct4_coord8.log   rerun_struct7_coord9.log
rerun_struct0_coord6.out    rerun_struct1_coord7.out   rerun_struct4_coord8.out   rerun_struct7_coord9.out
rerun_struct0_coord6.xvg    rerun_struct1_coord7.xvg   rerun_struct4_coord8.xvg   rerun_struct7_coord9.xvg
rerun_struct0_coord7.edr    rerun_struct1_coord8.edr   rerun_struct4_coord9.edr   rerun_struct8_coord0.edr
rerun_struct0_coord7.log    rerun_struct1_coord8.log   rerun_struct4_coord9.log   rerun_struct8_coord0.log
rerun_struct0_coord7.out    rerun_struct1_coord8.out   rerun_struct4_coord9.out   rerun_struct8_coord0.out
rerun_struct0_coord7.xvg    rerun_struct1_coord8.xvg   rerun_struct4_coord9.xvg   rerun_struct8_coord0.xvg
rerun_struct0_coord8.edr    rerun_struct1_coord9.edr   rerun_struct5_coord0.edr   rerun_struct8_coord10.edr
rerun_struct0_coord8.log    rerun_struct1_coord9.log   rerun_struct5_coord0.log   rerun_struct8_coord10.log
rerun_struct0_coord8.out    rerun_struct1_coord9.out   rerun_struct5_coord0.out   rerun_struct8_coord10.out
rerun_struct0_coord8.xvg    rerun_struct1_coord9.xvg   rerun_struct5_coord0.xvg   rerun_struct8_coord10.xvg
rerun_struct0_coord9.edr    rerun_struct2_coord0.edr   rerun_struct5_coord10.edr  rerun_struct8_coord11.edr
rerun_struct0_coord9.log    rerun_struct2_coord0.log   rerun_struct5_coord10.log  rerun_struct8_coord11.log
rerun_struct0_coord9.out    rerun_struct2_coord0.out   rerun_struct5_coord10.out  rerun_struct8_coord11.out
rerun_struct0_coord9.xvg    rerun_struct2_coord0.xvg   rerun_struct5_coord10.xvg  rerun_struct8_coord11.xvg
rerun_struct10_coord0.edr   rerun_struct2_coord10.edr  rerun_struct5_coord11.edr  rerun_struct8_coord1.edr
rerun_struct10_coord0.log   rerun_struct2_coord10.log  rerun_struct5_coord11.log  rerun_struct8_coord1.log
rerun_struct10_coord0.out   rerun_struct2_coord10.out  rerun_struct5_coord11.out  rerun_struct8_coord1.out
rerun_struct10_coord0.xvg   rerun_struct2_coord10.xvg  rerun_struct5_coord11.xvg  rerun_struct8_coord1.xvg
rerun_struct10_coord10.edr  rerun_struct2_coord11.edr  rerun_struct5_coord1.edr   rerun_struct8_coord2.edr
rerun_struct10_coord10.log  rerun_struct2_coord11.log  rerun_struct5_coord1.log   rerun_struct8_coord2.log
rerun_struct10_coord10.out  rerun_struct2_coord11.out  rerun_struct5_coord1.out   rerun_struct8_coord2.out
rerun_struct10_coord10.xvg  rerun_struct2_coord11.xvg  rerun_struct5_coord1.xvg   rerun_struct8_coord2.xvg
rerun_struct10_coord11.edr  rerun_struct2_coord1.edr   rerun_struct5_coord2.edr   rerun_struct8_coord3.edr
rerun_struct10_coord11.log  rerun_struct2_coord1.log   rerun_struct5_coord2.log   rerun_struct8_coord3.log
rerun_struct10_coord11.out  rerun_struct2_coord1.out   rerun_struct5_coord2.out   rerun_struct8_coord3.out
rerun_struct10_coord11.xvg  rerun_struct2_coord1.xvg   rerun_struct5_coord2.xvg   rerun_struct8_coord3.xvg
rerun_struct10_coord1.edr   rerun_struct2_coord2.edr   rerun_struct5_coord3.edr   rerun_struct8_coord4.edr
rerun_struct10_coord1.log   rerun_struct2_coord2.log   rerun_struct5_coord3.log   rerun_struct8_coord4.log
rerun_struct10_coord1.out   rerun_struct2_coord2.out   rerun_struct5_coord3.out   rerun_struct8_coord4.out
rerun_struct10_coord1.xvg   rerun_struct2_coord2.xvg   rerun_struct5_coord3.xvg   rerun_struct8_coord4.xvg
rerun_struct10_coord2.edr   rerun_struct2_coord3.edr   rerun_struct5_coord4.edr   rerun_struct8_coord5.edr
rerun_struct10_coord2.log   rerun_struct2_coord3.log   rerun_struct5_coord4.log   rerun_struct8_coord5.log
rerun_struct10_coord2.out   rerun_struct2_coord3.out   rerun_struct5_coord4.out   rerun_struct8_coord5.out
rerun_struct10_coord2.xvg   rerun_struct2_coord3.xvg   rerun_struct5_coord4.xvg   rerun_struct8_coord5.xvg
rerun_struct10_coord3.edr   rerun_struct2_coord4.edr   rerun_struct5_coord5.edr   rerun_struct8_coord6.edr
rerun_struct10_coord3.log   rerun_struct2_coord4.log   rerun_struct5_coord5.log   rerun_struct8_coord6.log
rerun_struct10_coord3.out   rerun_struct2_coord4.out   rerun_struct5_coord5.out   rerun_struct8_coord6.out
rerun_struct10_coord3.xvg   rerun_struct2_coord4.xvg   rerun_struct5_coord5.xvg   rerun_struct8_coord6.xvg
rerun_struct10_coord4.edr   rerun_struct2_coord5.edr   rerun_struct5_coord6.edr   rerun_struct8_coord7.edr
rerun_struct10_coord4.log   rerun_struct2_coord5.log   rerun_struct5_coord6.log   rerun_struct8_coord7.log
rerun_struct10_coord4.out   rerun_struct2_coord5.out   rerun_struct5_coord6.out   rerun_struct8_coord7.out
rerun_struct10_coord4.xvg   rerun_struct2_coord5.xvg   rerun_struct5_coord6.xvg   rerun_struct8_coord7.xvg
rerun_struct10_coord5.edr   rerun_struct2_coord6.edr   rerun_struct5_coord7.edr   rerun_struct8_coord8.edr
rerun_struct10_coord5.log   rerun_struct2_coord6.log   rerun_struct5_coord7.log   rerun_struct8_coord8.log
rerun_struct10_coord5.out   rerun_struct2_coord6.out   rerun_struct5_coord7.out   rerun_struct8_coord8.out
rerun_struct10_coord5.xvg   rerun_struct2_coord6.xvg   rerun_struct5_coord7.xvg   rerun_struct8_coord8.xvg
rerun_struct10_coord6.edr   rerun_struct2_coord7.edr   rerun_struct5_coord8.edr   rerun_struct8_coord9.edr
rerun_struct10_coord6.log   rerun_struct2_coord7.log   rerun_struct5_coord8.log   rerun_struct8_coord9.log
rerun_struct10_coord6.out   rerun_struct2_coord7.out   rerun_struct5_coord8.out   rerun_struct8_coord9.out
rerun_struct10_coord6.xvg   rerun_struct2_coord7.xvg   rerun_struct5_coord8.xvg   rerun_struct8_coord9.xvg
rerun_struct10_coord7.edr   rerun_struct2_coord8.edr   rerun_struct5_coord9.edr   rerun_struct9_coord0.edr
rerun_struct10_coord7.log   rerun_struct2_coord8.log   rerun_struct5_coord9.log   rerun_struct9_coord0.log
rerun_struct10_coord7.out   rerun_struct2_coord8.out   rerun_struct5_coord9.out   rerun_struct9_coord0.out
rerun_struct10_coord7.xvg   rerun_struct2_coord8.xvg   rerun_struct5_coord9.xvg   rerun_struct9_coord0.xvg
rerun_struct10_coord8.edr   rerun_struct2_coord9.edr   rerun_struct6_coord0.edr   rerun_struct9_coord10.edr
rerun_struct10_coord8.log   rerun_struct2_coord9.log   rerun_struct6_coord0.log   rerun_struct9_coord10.log
rerun_struct10_coord8.out   rerun_struct2_coord9.out   rerun_struct6_coord0.out   rerun_struct9_coord10.out
rerun_struct10_coord8.xvg   rerun_struct2_coord9.xvg   rerun_struct6_coord0.xvg   rerun_struct9_coord10.xvg
rerun_struct10_coord9.edr   rerun_struct3_coord0.edr   rerun_struct6_coord10.edr  rerun_struct9_coord11.edr
rerun_struct10_coord9.log   rerun_struct3_coord0.log   rerun_struct6_coord10.log  rerun_struct9_coord11.log
rerun_struct10_coord9.out   rerun_struct3_coord0.out   rerun_struct6_coord10.out  rerun_struct9_coord11.out
rerun_struct10_coord9.xvg   rerun_struct3_coord0.xvg   rerun_struct6_coord10.xvg  rerun_struct9_coord11.xvg
rerun_struct11_coord0.edr   rerun_struct3_coord10.edr  rerun_struct6_coord11.edr  rerun_struct9_coord1.edr
rerun_struct11_coord0.log   rerun_struct3_coord10.log  rerun_struct6_coord11.log  rerun_struct9_coord1.log
rerun_struct11_coord0.out   rerun_struct3_coord10.out  rerun_struct6_coord11.out  rerun_struct9_coord1.out
rerun_struct11_coord0.xvg   rerun_struct3_coord10.xvg  rerun_struct6_coord11.xvg  rerun_struct9_coord1.xvg
rerun_struct11_coord10.edr  rerun_struct3_coord11.edr  rerun_struct6_coord1.edr   rerun_struct9_coord2.edr
rerun_struct11_coord10.log  rerun_struct3_coord11.log  rerun_struct6_coord1.log   rerun_struct9_coord2.log
rerun_struct11_coord10.out  rerun_struct3_coord11.out  rerun_struct6_coord1.out   rerun_struct9_coord2.out
rerun_struct11_coord10.xvg  rerun_struct3_coord11.xvg  rerun_struct6_coord1.xvg   rerun_struct9_coord2.xvg
rerun_struct11_coord11.edr  rerun_struct3_coord1.edr   rerun_struct6_coord2.edr   rerun_struct9_coord3.edr
rerun_struct11_coord11.log  rerun_struct3_coord1.log   rerun_struct6_coord2.log   rerun_struct9_coord3.log
rerun_struct11_coord11.out  rerun_struct3_coord1.out   rerun_struct6_coord2.out   rerun_struct9_coord3.out
rerun_struct11_coord11.xvg  rerun_struct3_coord1.xvg   rerun_struct6_coord2.xvg   rerun_struct9_coord3.xvg
rerun_struct11_coord1.edr   rerun_struct3_coord2.edr   rerun_struct6_coord3.edr   rerun_struct9_coord4.edr
rerun_struct11_coord1.log   rerun_struct3_coord2.log   rerun_struct6_coord3.log   rerun_struct9_coord4.log
rerun_struct11_coord1.out   rerun_struct3_coord2.out   rerun_struct6_coord3.out   rerun_struct9_coord4.out
rerun_struct11_coord1.xvg   rerun_struct3_coord2.xvg   rerun_struct6_coord3.xvg   rerun_struct9_coord4.xvg
rerun_struct11_coord2.edr   rerun_struct3_coord3.edr   rerun_struct6_coord4.edr   rerun_struct9_coord5.edr
rerun_struct11_coord2.log   rerun_struct3_coord3.log   rerun_struct6_coord4.log   rerun_struct9_coord5.log
rerun_struct11_coord2.out   rerun_struct3_coord3.out   rerun_struct6_coord4.out   rerun_struct9_coord5.out
rerun_struct11_coord2.xvg   rerun_struct3_coord3.xvg   rerun_struct6_coord4.xvg   rerun_struct9_coord5.xvg
rerun_struct11_coord3.edr   rerun_struct3_coord4.edr   rerun_struct6_coord5.edr   rerun_struct9_coord6.edr
rerun_struct11_coord3.log   rerun_struct3_coord4.log   rerun_struct6_coord5.log   rerun_struct9_coord6.log
rerun_struct11_coord3.out   rerun_struct3_coord4.out   rerun_struct6_coord5.out   rerun_struct9_coord6.out
rerun_struct11_coord3.xvg   rerun_struct3_coord4.xvg   rerun_struct6_coord5.xvg   rerun_struct9_coord6.xvg
rerun_struct11_coord4.edr   rerun_struct3_coord5.edr   rerun_struct6_coord6.edr   rerun_struct9_coord7.edr
rerun_struct11_coord4.log   rerun_struct3_coord5.log   rerun_struct6_coord6.log   rerun_struct9_coord7.log
rerun_struct11_coord4.out   rerun_struct3_coord5.out   rerun_struct6_coord6.out   rerun_struct9_coord7.out
rerun_struct11_coord4.xvg   rerun_struct3_coord5.xvg   rerun_struct6_coord6.xvg   rerun_struct9_coord7.xvg
rerun_struct11_coord5.edr   rerun_struct3_coord6.edr   rerun_struct6_coord7.edr   rerun_struct9_coord8.edr
rerun_struct11_coord5.log   rerun_struct3_coord6.log   rerun_struct6_coord7.log   rerun_struct9_coord8.log
rerun_struct11_coord5.out   rerun_struct3_coord6.out   rerun_struct6_coord7.out   rerun_struct9_coord8.out
rerun_struct11_coord5.xvg   rerun_struct3_coord6.xvg   rerun_struct6_coord7.xvg   rerun_struct9_coord8.xvg
rerun_struct11_coord6.edr   rerun_struct3_coord7.edr   rerun_struct6_coord8.edr   rerun_struct9_coord9.edr
rerun_struct11_coord6.log   rerun_struct3_coord7.log   rerun_struct6_coord8.log   rerun_struct9_coord9.log
rerun_struct11_coord6.out   rerun_struct3_coord7.out   rerun_struct6_coord8.out   rerun_struct9_coord9.out
rerun_struct11_coord6.xvg   rerun_struct3_coord7.xvg   rerun_struct6_coord8.xvg   rerun_struct9_coord9.xvg
rerun_struct11_coord7.edr   rerun_struct3_coord8.edr   rerun_struct6_coord9.edr   unk_matrix.pkl
rerun_struct11_coord7.log   rerun_struct3_coord8.log   rerun_struct6_coord9.log
rerun_struct11_coord7.out   rerun_struct3_coord8.out   rerun_struct6_coord9.out
rerun_struct11_coord7.xvg   rerun_struct3_coord8.xvg   rerun_struct6_coord9.xvg`

(fep) cadd@huiyu:~/program/fep/workdir/fep$ bash runall.sh

environment: rerun/rerun_struct_coord.out: No such file or directory
environment: rerun/rerun_struct_coord.out: No such file or directory
environment: rerun/rerun_struct_coord.out: No such file or directory
environment: rerun/rerun_struct_coord.out: No such file or directory
environment: rerun/rerun_struct_coord.out: No such file or directory
environment: rerun/rerun_struct_coord.out: No such file or directory
environment: rerun/rerun_struct_coord.out: No such file or directory
environment: rerun/rerun_struct_coord.out: No such file or directory
environment: rerun/rerun_struct_coord.out: No such file or directory
environment: rerun/rerun_struct_coord.out: No such file or directory
environment: rerun/rerun_struct_coord.out: No such file or directory
environment: rerun/rerun_struct_coord.out: No such file or directory
environment: rerun/rerun_struct_coord.out: No such file or directory
environment: rerun/rerun_struct_coord.out: No such file or directory
environment: rerun/rerun_struct_coord.out: No such file or directory
environment: rerun/rerun_struct_coord.out: No such file or directory
environment: rerun/rerun_struct_coord.out: No such file or directory
environment: rerun/rerun_struct_coord.out: No such file or directory
environment: rerun/rerun_struct_coord.out: No such file or directory
environment: rerun/rerun_struct_coord.out: No such file or directory
environment: rerun/rerun_struct_coord.out: No such file or directory
environment: rerun/rerun_struct_coord.out: No such file or directory
environment: rerun/rerun_struct_coord.out: No such file or directory
environment: rerun/rerun_struct_coord.out: No such file or directory
tar: */water/md/lambda*/analysis.log: Cannot stat: No such file or directory
tar: */protein/md/lambda*/analysis.log: Cannot stat: No such file or directory
tar: */water/md/analysis/*.xvg: Cannot stat: No such file or directory
tar: */protein/md/analysis/*.xvg: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors

_Originally posted by @Lumen97 in https://github.com/luancarvalhomartins/PyAutoFEP/issues/56#issuecomment-1195046965_

**Comment by Moricant** [comment]
I seem to be encountering this consistently with both the tutorial data and my own systems. Has anyone come up with a fix or workaround?

**Comment by luancarvalhomartins** [comment]
Sorry, I could not work on a fix for this bug yet. I started working on a complete rewrite of the runscript that would also solve this issue. I will try to fix it in the current run script before pushing the massive changes.

**Comment by wangl-g** [comment]
I think there are typing errors in the last several lines. First,fn should be fn_pbc, ! -f xtc should be -f xtc, the !(not) should not present in the logical expression.
