### ISSUE TITLE
solute scaling failed with plumed

### ISSUE THREAD

**Issue by YunpengCai** [luancarvalhomartins/PyAutoFEP#62]
Hi, I wanted to use the REST2 method but encountered an error message.
I used argument -solute_scaling 1 --solute_scaling_bin=rest2 --solute_scaling_selection=LIG:.+ when calling prepare_dual_topology.py.
But an error occured said [DEBUG] Saving a copy of edited topology submitted to REST bin /home/program/PyAutoFEP/Tools/rest2.sh in file /tmp/tmp3cuc2vie/workspace/ligand_1-ligand_2/water/lambda0/fullsystem_171230_13092022_altered_topology_backup.top
[ERROR] Plumed failed with the message:
[ERROR] ERROR: in atomtypes.
Is there something wrong with my arguments or this method has not been fully implemented yet?

**Comment by YunpengCai** [comment]
Please have a look at the attached log and top files.

BTW, I commeted some of your conformer searching codes in merge_topologies.py, as I have already aligned ligands' conformation well in Schrodinger. Otherwise, it will raise errors such as `EmbedMultipleConfs failed to generate conformations` and `Failed to match molecule in constrained_embed_forcefield. Cannot continue.` Hope this is not the cause of failure.

[fullsystem_110333_14092022_altered_topology_backup.top.txt](https://github.com/luancarvalhomartins/PyAutoFEP/files/9562364/fullsystem_110333_14092022_altered_topology_backup.top.txt)
[log.txt](https://github.com/luancarvalhomartins/PyAutoFEP/files/9562366/log.txt)

**Comment by luancarvalhomartins** [comment]
Sorry for the tardiness. 

I think I fixed the bug. I'm committing a patch today.

**Comment by YunpengCai** [comment]
Thanks for your hard work on the patch! 
Unfortunately, after merging your updates, the REST2 still raise the same error `[ERROR] Plumed failed with the message: ERROR: in atomtypes`. I've been reading plumed forum and saw it happened to many people when using Plumed. 
Maybe this is not your code problem. But can I ask for the test file you are using in order to compare?  Such as you input `ligands` and `protein`, as well as the `altered_topology.top' files

**Comment by luancarvalhomartins** [comment]
Sure, find it attached.

**Comment by YunpengCai** [comment]
Thanks, I found out it was caused by the topology file format I used, as I was using my own forcefield instead of what you used. Maybe it is safe to close the issue now.

**Comment by luancarvalhomartins** [comment]
Thanks for letting me known.
