### ISSUE TITLE
tar: /water/md/lambda/lambda_pbcfit.xtc: Cannot stat: No such file or directory

### ISSUE THREAD

**Issue by Lumen97** [luancarvalhomartins/PyAutoFEP#71]
Dear han-ri.

Thank you very much for your message and sorry for the tardiness.

> Do I need the analysis.log file and xvg file of the water to proceed with the analysis step?
Currently, there is no analysis performed on the water leg, but I hope to add some analysis at some point. No, that files are not required by the analysis step and this error can be ignored. Sorry about that.

I had just committed a patch that fix this issue.

_Originally posted by @luancarvalhomartins in https://github.com/luancarvalhomartins/PyAutoFEP/issues/69#issuecomment-1379485462_

**Comment by Lumen97** [comment]
The error still exists now.

$ bash runall.sh
tar: /water/md/lambda/lambda_pbcfit.xtc: Cannot stat: No such file or directory
tar: /water/md/lambda/analysis.log: Cannot stat: No such file or directory
tar: /{protein}/md/analysis/.xvg: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors.

**Comment by Lumen97** [comment]
![image](https://user-images.githubusercontent.com/74954182/226788047-94036ff7-c598-4f65-86d4-841cea701cd5.png)
In addition, there is a syntax error in output_files_data.ini.

**Comment by luancarvalhomartins** [comment]
Thanks for reporting. Just fixed.
