### ISSUE TITLE
Select the terms you want from the following list by

### ISSUE THREAD

**Issue by Blockbastermaker** [luancarvalhomartins/PyAutoFEP#72]

**Comment by luancarvalhomartins** [comment]
Dear @Blockbastermaker,

Would you mind further describing your issue? When does this error shows up? Would you mind posting the full output?

Thank you.

**Comment by luancarvalhomartins** [comment]
Due to inactivity, I am closing this issue. Should you still face this problem, feel free to reopen.

Thank you!
