### ISSUE TITLE
Unknown command-line option -plumed -hrex

### ISSUE THREAD

**Issue by 1200Caixia** [luancarvalhomartins/PyAutoFEP#73]
I was reported 'Unknown command-line option -plumed -hrex', when I run 'gmx_mpi mdrun -v --deffnm lambda -cpi lambda.cpt -multidir lambda0 lambda1 lambda2 lambda3 ... -plumed plumed.dat -hrex -replex 500'. how can I solve this problem?

**Comment by luancarvalhomartins** [comment]
It seems your GROMACS install is not patched with Plumed. Would you mind confirming that you can use command line options `-plumed -hrex` using this GROMACS binary?

See further info at Plumed manual: https://www.plumed.org/doc-v2.8/user-doc/html/_installation.html

**Comment by 1200Caixia** [comment]
Thank you for your manual. It helped me solve this problem.
