### ISSUE TITLE
Tutorial. Analysis, error with libfuse2

### ISSUE THREAD

**Issue by knawel** [luancarvalhomartins/PyAutoFEP#75]
Hi,
Thank you for your project! I faced an error during the analysis. When I run `analyze_results.py` I have got:

```
All available analysis will be run
================== Pairwise ΔΔG ==================
         Perturbation           protein    water  

=================== STACK INFO ===================
  File "../PyAutoFEP/analyze_results.py", line 1820, in <module>
    ddg_to_center = ddg_to_center_ddg(saved_data['perturbation_map'], center=arguments.center_molecule,
  File "../PyAutoFEP/analyze_results.py", line 1034, in ddg_to_center_ddg
    os_util.local_print('Could not find a path to connect nodes {} and {}. Cannot go on. Check the '
  File "/data/calc/FEP/PyAutoFEP/os_util.py", line 311, in local_print
    formatted_string = '\n{:=^50}\n{}{:=^50}\n'.format(' STACK INFO ', ''.join(traceback.format_stack()),
=================== STACK INFO ===================
[ERROR] Could not find a path to connect nodes FXR_74 and FXR_12. Cannot go on. Check the  perturbations and your input graph. Alternatively, rerun with no_checks to force execution and ignore this error.
Traceback (most recent call last):
  File "../PyAutoFEP/analyze_results.py", line 1024, in ddg_to_center_ddg
    ddg_to_center[each_node] = sum_path(ddg_graph, each_path, ddg_key=ddg_key)
  File "../PyAutoFEP/analyze_results.py", line 986, in sum_path
    raise networkx.exception.NetworkXNoPath('Edge between {} {} not found in graph {}'.format(node_i, node_j, g0))
networkx.exception.NetworkXNoPath: Edge between FXR_12 FXR_74 not found in graph DiGraph with 3 nodes and 2 edges

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../PyAutoFEP/analyze_results.py", line 1820, in <module>
    ddg_to_center = ddg_to_center_ddg(saved_data['perturbation_map'], center=arguments.center_molecule,
  File "../PyAutoFEP/analyze_results.py", line 1040, in ddg_to_center_ddg
    raise networkx.exception.NetworkXNoPath(error)
networkx.exception.NetworkXNoPath: Edge between FXR_12 FXR_74 not found in graph DiGraph with 3 nodes and 2 edges
```

Digging into that problem, I found that on fresh Ubuntu 22.04, the script `collect_results_from_xvg` doesn't work; it requires the `libfuse2` library (which can be installed via `apt install libfuse2`). So maybe this package can be added to the requirements? 

The related to that package issue is an installation using a Docker container. It's not easy to install ([example of that issue](https://github.com/moby/moby/issues/514). So, it is not possible to properly run `runall.sh` using the Docker container. Is it possible to divide this stage into two: MD and collect results? It would allow running MD on Docker and later collect results on the computer with the installed fuse.

**Comment by luancarvalhomartins** [comment]
Thanks for your comment and sorry about the late reply. I started a position in industry and my time is now quite limited.

`libfuse2` is a requirement of the packing scheme I am using to generate the `collect_results_from_xvg` binary from python. I don't think it would be easy to replace that, but I believe there is a much simpler solution: set `output_collecttype=python` and make sure you have a `python3` in path during runtime. Maybe now that python3 is mainlined for a while, I could make that default and add a comment on the requirements.

Regarding your original problem, it seems one of the legs did not run. Double check your `FXR_12-FXR_74/{water,protein}/md/lambda*` directories.
