### ISSUE TITLE
[Suggestions] Add `maxMatches` for `get_substruct_matches_fallback`

### ISSUE THREAD

**Issue by Dead-fisher** [luancarvalhomartins/PyAutoFEP#76]
Hi,

I suggest adding "maxMatches=xxx" in function here:
https://github.com/luancarvalhomartins/PyAutoFEP/blob/c45433ab1fc0f14bdc40e1320338894bf52e67d4/merge_topologies.py#L1553

The reason is that,  when I generate the `achiral_matches_a` for my ligands, the length of it is over 700, which yield the `achiral_matches_a`*`achiral_matches_b` to explosion. The whole process is therefore stalled here for a extrmely long time.

Also, `rdkit` recommend using the 'maxMatches' to restrain the number of matches and prevent the explosion when using `GetSubstructMatches`. ref: https://www.rdkit.org/docs/source/rdkit.Chem.rdchem.html

I also exaime the result here, where even I use 'maxMatches=20', the results are fine enough.

I am not very sure how the number of matches can influence the final result but a explision of matches will stall the process.

Any suggestions here?

 Thanks!

**Comment by luancarvalhomartins** [comment]
Awesome suggestion. Thank you very much. I think that that may matches is only possible in find_3d_mcs when the first guess of the asymmetric MCS is tiny and too many matches are possible. I work on a patch lowering the limit to something more resonable.

Thank you
