### ISSUE TITLE
/usr/bin/bash: fn_pbc: command not found

### ISSUE THREAD

**Issue by Lumen97** [luancarvalhomartins/PyAutoFEP#80]
Hello, I encountered the following error message while running:

(fep) cadd@huiyu:/media/cadd/1857f441-374b-4242-a78d-007ca5df83ce/data/fep/pyautoFEP/test_amber14/fep$ bash runall.sh
/usr/bin/bash: fn_pbc: command not found
tar: /protein/md/lambda/lambda_pbcfit.xtc: Cannot stat: No such file or directory
tar: /water/md/lambda/lambda.xtc: Cannot stat: No such file or directory

I believe that at line 225 of output_files_data.ini, "export -f fn" should be changed to "export -f fn_pbc". At line 228, if there is no file named "lambda*/lambda_pbcfit.xtc", even when the number of files is 0, the code _if [ $(ls lambda*/lambda_pbcfit.xtc 2>/dev/null | wc -l) -ne ${n_lambda} ]_ will have an error of" unary operator expected ", I am not sure how to make the correct modifications here. For now, use _if [- n "$projectory_files"]_ instead。

As for the final error message 'tar:/water/md/lambda/lambda. xtc: unable to count: no such file or directory', may I ask if this has any impact on the final result and what is the purpose of packaging this file?  It seems that the file was not used during operation.

```
`export -f fn

           trajectory_files=$(ls -v lambda*/lambda.tpr)
           if [ $(ls lambda*/lambda_pbcfit.xtc 2>/dev/null | wc -l) -ne ${n_lambda} ]
           then
               parallel --jobs=1 --joblog analysis_joblog_$(date "+%H%M%S_%d%m%Y").log --env fn_pbc --env pbc_cluster 'cd {//} && [ ! -f "{.}_pbcfit.xtc" ] && fn_pbc' ::: ${trajectory_files}
           fi`
```

**Comment by luancarvalhomartins** [comment]
Sorry for the tardiness. I started a position in industry and the time I can work on PyAutoFEP is (for now) very limited.

Thank you very much for the suggestions.

1. Thanks about `export -f fn`. Fixed, will commit in a moment
2. What is your bash version? I tested using `5.2` and `5.0` and both worked. The code was meant to count that every available tpr (not) yielded a lambda_pbcfit.xtc, so not the same as `[ -n "$trajectory_files" ]`. In case it is not working on a resonably new version, I will have to figure out another solution.
3. No, packing has no effect on the results. It's meant as a convenience for the user to download the results and trajectories a single file (eg, when you are running on a cluster)
