### ISSUE TITLE
Atom type oplsm_298 specified in terminal database has not been defined in the force field

### ISSUE THREAD

**Issue by chaoyangma24** [luancarvalhomartins/PyAutoFEP#82]
Thank for your devotion to the calculation of free energy between protein and ligand by gromacs.
When I run prepare_dual_topology.py --config_file=step2.ini, there appears the following errors. Your reply would be very appreciated.

[ERROR] Failed to run gmx pdb2gmx. Error code 1.
[ERROR] Command line was: ['gmx', 'pdb2gmx', '-f', 'receptor_data/5q17_processed.pdb', '-p', '/tmp/tmpv8zsyvyl/tutorial/FXR_12-FXR_74/protein/build_system_133841_24042023/protein_step1_133841_24042023.top', '-o', '/tmp/tmpv8zsyvyl/tutorial/FXR_12-FXR_74/protein/build_system_133841_24042023/protein_step1_133841_24042023.pdb']
[ERROR] 
[ERROR] stdout:
[ERROR] Select the Force Field:
[ERROR] 
[ERROR] From current directory:
[ERROR] 
[ERROR]  1: OPLS-AA/M all-atom force field (2015 aminoacid dihedrals)
[ERROR] 
[ERROR] From '/home/chaoyang/gromacs-2023/share/top':
[ERROR] 
[ERROR]  2: AMBER03 protein, nucleic AMBER94 (Duan et al., J. Comp. Chem. 24, 1999-2012, 2003)
[ERROR] 
[ERROR]  3: AMBER94 force field (Cornell et al., JACS 117, 5179-5197, 1995)
[ERROR] 
[ERROR]  4: AMBER96 protein, nucleic AMBER94 (Kollman et al., Acc. Chem. Res. 29, 461-469, 1996)
[ERROR] 
[ERROR]  5: AMBER99 protein, nucleic AMBER94 (Wang et al., J. Comp. Chem. 21, 1049-1074, 2000)
[ERROR] 
[ERROR]  6: AMBER99SB protein, nucleic AMBER94 (Hornak et al., Proteins 65, 712-725, 2006)
[ERROR] 
[ERROR]  7: AMBER99SB-ILDN protein, nucleic AMBER94 (Lindorff-Larsen et al., Proteins 78, 1950-58, 2010)
[ERROR] 
[ERROR]  8: AMBERGS force field (Garcia & Sanbonmatsu, PNAS 99, 2782-2787, 2002)
[ERROR] 
[ERROR]  9: CHARMM27 all-atom force field (CHARM22 plus CMAP for proteins)
[ERROR] 
[ERROR] 10: GROMOS96 43a1 force field
[ERROR] 
[ERROR] 11: GROMOS96 43a2 force field (improved alkane dihedrals)
[ERROR] 
[ERROR] 12: GROMOS96 45a3 force field (Schuler JCC 2001 22 1205)
[ERROR] 
[ERROR] 13: GROMOS96 53a5 force field (JCC 2004 vol 25 pag 1656)
[ERROR] 
[ERROR] 14: GROMOS96 53a6 force field (JCC 2004 vol 25 pag 1656)
[ERROR] 
[ERROR] 15: GROMOS96 54a7 force field (Eur. Biophys. J. (2011), 40,, 843-856, DOI: 10.1007/s00249-011-0700-9)
[ERROR] 
[ERROR] 16: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
[ERROR] 
[ERROR] Using the Oplsaam force field in directory ./oplsaam.ff
[ERROR] 
[ERROR] Select the Water Model:
[ERROR] 
[ERROR]  1: TIP4P  TIP 4-point, recommended
[ERROR] 
[ERROR]  2: TIP3P  TIP 3-point
[ERROR] 
[ERROR]  3: TIP5P  TIP 5-point (see http://redmine.gromacs.org/issues/1348 for issues)
[ERROR] 
[ERROR]  4: TIP5P  TIP 5-point improved for Ewald sums
[ERROR] 
[ERROR]  5: SPC    simple point charge
[ERROR] 
[ERROR]  6: SPC/E  extended simple point charge
[ERROR] 
[ERROR]  7: None
[ERROR] 
[ERROR] going to rename ./oplsaam.ff/aminoacids.r2b
[ERROR] Reading receptor_data/5q17_processed.pdb...
[ERROR] Read '', 3871 atoms
[ERROR] 
[ERROR] Analyzing pdb file
[ERROR] Splitting chemical chains based on TER records or chain id changing.
[ERROR] 
[ERROR] There are 2 chains and 0 blocks of water and 236 residues with 3871 atoms
[ERROR] 
[ERROR]   chain  #res #atoms
[ERROR] 
[ERROR]   1 ' '   224   3662  
[ERROR] 
[ERROR]   2 ' '    12    209  
[ERROR] 
[ERROR] there were 2106 atoms with zero occupancy and 1765 atoms with          occupancy unequal to one (out of 3871 atoms). Check your pdb file.
[ERROR] 
[ERROR] Reading residue database... (Oplsaam)
[ERROR] 
[ERROR] 
[ERROR] stderr:
[ERROR]                       :-) GROMACS - gmx pdb2gmx, 2023 (-:
[ERROR] 
[ERROR] Executable:   /home/chaoyang/gromacs-2023/build/bin/./gmx_mpi
[ERROR] Data prefix:  /home/chaoyang/gromacs-2023 (source tree)
[ERROR] Working dir:  /home/chaoyang/PyAutoFEP/workdir
[ERROR] Command line:
[ERROR]   gmx pdb2gmx -f receptor_data/5q17_processed.pdb -p /tmp/tmpv8zsyvyl/tutorial/FXR_12-FXR_74/protein/build_system_133841_24042023/protein_step1_133841_24042023.top -o /tmp/tmpv8zsyvyl/tutorial/FXR_12-FXR_74/protein/build_system_133841_24042023/protein_step1_133841_24042023.pdb
[ERROR] 
[ERROR] Opening force field file ./oplsaam.ff/watermodels.dat
[ERROR] Opening force field file ./oplsaam.ff/aminoacids.r2b
[ERROR] there were 2106 atoms with zero occupancy and 1765 atoms with          occupancy unequal to one (out of 3871 atoms). Check your pdb file.
[ERROR] Opening force field file ./oplsaam.ff/atomtypes.atp
[ERROR] Opening force field file ./oplsaam.ff/aminoacids.rtp
[ERROR] Opening force field file ./oplsaam.ff/aminoacids.hdb
[ERROR] Opening force field file ./oplsaam.ff/aminoacids.n.tdb
[ERROR] 
[ERROR] -------------------------------------------------------
[ERROR] Program:     gmx pdb2gmx, version 2023
[ERROR] Source file: src/gromacs/gmxpreprocess/ter_db.cpp (line 138)
[ERROR] Function:    void read_atom(char*, bool, std::string*, t_atom*, PreprocessingAtomTypes*, int*)
[ERROR] 
[ERROR] Inconsistency in user input:
[ERROR] Atom type oplsm_298 specified in terminal database has not been defined in the
[ERROR] force field
[ERROR] 
[ERROR] For more information and tips for troubleshooting, please check the GROMACS
[ERROR] website at http://www.gromacs.org/Documentation/Errors
[ERROR] -------------------------------------------------------
[ERROR]

**Comment by luancarvalhomartins** [comment]
Thank you for your message.

That's probably #42 (an upstream issue with OPLS FF atomtypes syntax). See #42 for possible fixes.

Feel free to comment here in case that is not your case.
