### ISSUE TITLE
perturbation_map

### ISSUE THREAD

**Issue by jiaming28** [luancarvalhomartins/PyAutoFEP#87]
I have 11 ligands and want to generate 10 perturbation pairs, but any one of the three map types (star, wheel, and optimal) can not generate the whole pairs I want to get. How can I solve this problem?

**Comment by luancarvalhomartins** [comment]
Thank you for your question. 

Are you trying to generate pairs that  form no graph of star, wheel or optimal, correct? If so, the simplest solution is passing a custom perturbation map to `prepare_dual_topology.py` using the `pertubation_map`option. See manual page 31. In brief,you will have to pass a file like this (where ligX is the name of your ligands):

```
lig1 lig2
lig2 lig3
lig3 lig4
```

**Comment by luancarvalhomartins** [comment]
Hope that solves your question. Should you need more info, feel free to reopen - or fill another issue.
