### ISSUE TITLE
Tutorial fails at tutorial/FXR_12-FXR_74/protein/lambda1/min01

### ISSUE THREAD

**Issue by JecaTosovic** [luancarvalhomartins/PyAutoFEP#92]
Hello.
Thank you for working on PyAutoFEP!

I'm working on the tutorial from the documentation. I'm using GROMACS version 2022.5 on linux. After fixing a couple of issues ( missing forcefield parameters and issues with /tmp not being on the same filesystem) I was able to get to the running stage.
However upon running `bash runall.sh` the job running in tutorial/FXR_12-FXR_74/protein/lambda1/min01 fails with maximum number of warnings(4) larger then -maxwarn of 3.

These are the warnings

 gmx_mpi grompp -c FXR_12-FXR_74/protein/lambda1/min01/../FullSystem.pdb -r FXR_12-FXR_74/protein/lambda1/min01/../FullSystem.pdb -f FXR_12-FXR_74/protein/lambda1/min01/min01.mdp -p FXR_12-FXR_74/protein/lambda1/min01/../SystemFull.top -o FXR_12-FXR_74/protein/lambda1/min01/min01.tpr -n FXR_12-FXR_74/protein/lambda1/min01/../index.ndx -po FXR_12-FXR_74/protein/lambda1/min01/min01_mdout.mdp -maxwarn 3

Ignoring obsolete mdp entry 'ns-type'
Generating 1-4 interactions: fudge = 0.5

WARNING 1 [file SystemFull.top, line 59]:
  The following macros were defined in the 'define' mdp field with the -D
  prefix, but were not used in the topology:
      POSRES_LIG
  If you haven't made a spelling error, either use the macro you defined,
  or don't define the macro

NOTE 1 [file SystemFull.top, line 59]:
  System has non-zero total charge: 0.003125
  Total charge should normally be an integer. See
  http://www.gromacs.org/Documentation/Floating_Point_Arithmetic
  for discussion on how close it should be to an integer.

WARNING 2 [file SystemFull.top, line 59]:
  You are using Ewald electrostatics in a system with net charge. This can
  lead to severe artifacts, such as ions moving into regions with low
  dielectric, due to the uniform background charge. We suggest to
  neutralize your system with counter ions, possibly in combination with a
  physiological salt concentration.

(more than 20 non-matching atom names)

WARNING 3 [file SystemFull.top, line 59]:
  58 non-matching atom names
  atom names from FXR_12-FXR_74/protein/lambda1/min01/../SystemFull.top will
  be used
  atom names from FXR_12-FXR_74/protein/lambda1/min01/../FullSystem.pdb
  will be ignored

The last warning I observed was similar to #66 :
Number of degrees of freedom in T-Coupling group rest is 71542.00

WARNING 4 [file FXR_12-FXR_74/protein/lambda1/min01/min01.mdp]:
  The largest distance between excluded atoms is 1.063 nm, which is larger
  than the cut-off distance. This will lead to missing long-range
  corrections in the forces and energies. If you expect that minimization
  will bring such distances within the cut-off, you can ignore this warning.

NOTE 2 [file FXR_12-FXR_74/protein/lambda1/min01/min01.mdp]:
  Removing center of mass motion in the presence of position restraints
  might cause artifacts. When you are using position restraints to
  equilibrate a macro-molecule, the artifacts are usually negligible.

There were 2 notes

There were 4 warnings

-------------------------------------------------------
Program:     gmx grompp, version 2022.5-dev
Source file: src/gromacs/gmxpreprocess/grompp.cpp (line 2661)

Fatal error:
Too many warnings (4).

I'm worried about 2nd and 3rd warning (non-zero and non-integer charge & non matching atom names).

It seems that the md run was successful in the case of the tutorial/FXR_12-FXR_74/protein/lambda0/ even though I observed the same atom naming problems.

**Comment by luancarvalhomartins** [comment]
Unfortunately, GROMACS 2022 is not currently supported (#66). Supporting it is WIP. Sorry about that.
