### ISSUE TITLE
The FEP calculation results are very different when rest2 is started and when rest2 is not started. 

### ISSUE THREAD

**Issue by 1200Caixia** [luancarvalhomartins/PyAutoFEP#94]
The FEP calculation results are very different when rest2 is started and when rest2 is not started.  The ddg for starting rest2 is much smaller than that for not starting REST2. I wonder if my calculations are correct. 

![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/115772938/14c1ddfd-3a23-4cf4-ae2f-ece5a8b27160)

**Comment by luancarvalhomartins** [comment]
Hum, something seems off. The legs with or without REST2 should agree to a certain extent.

Which is your REST2 region? How does the overlap matrix look?

**Comment by 1200Caixia** [comment]
My initial structure was wrong, and the ligands weren't properly docked into the pocket.
