### ISSUE TITLE
Using system loader (ie, a pre-solvated system) and pdb2gmx -ignh parameter

### ISSUE THREAD

**Issue by Tiamo6174** [luancarvalhomartins/PyAutoFEP#95]
First question: After reading the manual, I still do not clearly understand how to use the system loader manually, using the balanced system as the structural input, which always comes up with such a question, if possible, can you update a tutorial on how to use the system loader or ini sample file on using the system loader? Second problem: If using the automatic system builder, the hydrogen in the protein is always incorrect, I don't know how to enter the pbd2gmx-ingh parameter in the ini file to ignore this error!![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/125472952/8d862b89-ddcf-4dd0-aa74-2dd3cf2ed554)![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/125472952/a40d60b4-82ec-4784-9739-2510192c578b)![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/125472952/9dc8d4a5-fdd3-40b2-a3dd-889c9dd63d99)

**Comment by Tiamo6174** [comment]
> I'm not the author, but you can add the -ignh parameter by editing prepare_dual_topology.py; around line 313 you will see a list of parameters to be passed to pdb2gmx:
> 
> pdb2gmx_list = ['pdb2gmx', '-f', structure_file,
> 
> [with additional parameters on the following line completing the list].
> 
> You can add -ignh here, e.g.:
> 
> pdb2gmx_list = ['pdb2gmx', '-ignh', '-f', structure_file,
> 
> 
> 
> Haven't played with the system loader stuff you've been having a problem with but it looks like there is a problem with the conda environment as the MDAnalysis module is not found when the script tries to import it. Running "conda list" will tell you all of the modules you have installed in your current environment and if the MDAnalysis module is not listed try installing it, e.g. "conda install -c conda-forge MDAnalysis"

Hi！Thank you very much for your answer, I have successfully run this step and reached the next stage, I encountered the following error in the "runall.sh" step, may I ask whether this is caused by the error of gmx_mpi![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/125472952/e90e5667-3f9e-4061-8180-7f19581c8e98)

**Comment by luancarvalhomartins** [comment]
OK, first, by passing  `-ignh` to `gmx pdb2gmx` you are asking GROMACS to ignore any proton in your input file. This means that the protonation states in your input pdb will be lost. This is hardly what you want. If GROMACS is complaining about your atom names, the best solution would be to correct your input. I can add a `-ignh` flag, but I think that it is dangerous.

Regarding the error during the run step, please attach the GROMACS logs so we can help you. The `runall.sh` is not very informative (sorry about that).

**Comment by Tiamo6174** [comment]
> OK, first, by passing  `-ignh` to `gmx pdb2gmx` you are asking GROMACS to ignore any proton in your input file. This means that the protonation states in your input pdb will be lost. This is hardly what you want. If GROMACS is complaining about your atom names, the best solution would be to correct your input. I can add a `-ignh` flag, but I think that it is dangerous.
> 
> 
> 
> Regarding the error during the run step, please attach the GROMACS logs so we can help you. The `runall.sh` is not very informative (sorry about that).  

Dear professor,thank you for your guidance. After trying again, I successfully made PyAutoFEP run to runall.sh and ran it successfully for a period of time, but the following errors still occurred. By checking gromacs logs, I found that the following error occurred at the 35655 step of the nve stage of water/lambda7 in the first molecule. The following is the content of my step2.ini file, the error content of runall.sh, and the error content of gromacs in the nve stage. This is because I used the system builder to import an inappropriate system. How can I solve this problem？![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/125472952/4ea3dab2-a19d-4f1c-9158-df53db206042)![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/125472952/1e5c884e-5852-4cac-b0ac-7e2781542131)![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/125472952/d2062e02-1128-4dd8-aaad-3046aad4428a)![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/125472952/fe19a011-d6c0-44e4-b613-7650f786c4f5)

**Comment by Tiamo6174** [comment]
> OK, first, by passing  `-ignh` to `gmx pdb2gmx` you are asking GROMACS to ignore any proton in your input file. This means that the protonation states in your input pdb will be lost. This is hardly what you want. If GROMACS is complaining about your atom names, the best solution would be to correct your input. I can add a `-ignh` flag, but I think that it is dangerous.
> 
> 
> 
> Regarding the error during the run step, please attach the GROMACS logs so we can help you. The `runall.sh` is not very informative (sorry about that).  

Dear professor, hello and thank you for your guidance. After trying again, I successfully made PyAutoFEP run to runall.sh and ran it successfully for a period of time, but the following errors still occurred. By checking gromacs logs, I found that the following errors occurred at the 35655 step of the nve stage of water/lambda7 in the first molecule. The following is the contents of my step2.ini file, the error content of runall.sh, and the error content of gromacs in the nve stage. Is it caused by using mcs tpye=3d? But if I use mcs type=graph and PyAutoFEP reminds me to use mcs tpye=3d, how can I solve this problem？![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/125472952/772e55f8-5086-4b34-8d8a-420817669976)![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/125472952/e8f4ae8e-8979-4190-a578-14492f9c7d1c)![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/125472952/4d82b354-1984-4392-b673-e8356daea732)![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/125472952/08d2646a-23cd-472b-b92c-141074982fc9)![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/125472952/b600bd6c-2425-4249-83de-67eae1e2c76e)

**Comment by luancarvalhomartins** [comment]
Your system is unstable. Would you mind checking that the MCS for you pair makes sense? The MCS is printed with verbose output (`-vv`) and can also be checked by inspecting the constant, A and B parts in the ligand topology file. Often such crashes are caused by a wrong, too small MCS. 

Are you inverting stereocenters? If not, `mcs_type=graph` (the default) should work.

Note: you seem to be using a SLURM job to run `runall.sh`, but `runall.sh` was written to work with SLURM. Take a look at the manual, setting `output_runbefore` and using `output_scripttype=slurm` may save you some time.

**Comment by Tiamo6174** [comment]
> Your system is unstable. Would you mind checking that the MCS for you pair makes sense? The MCS is printed with verbose output (`-vv`) and can also be checked by inspecting the constant, A and B parts in the ligand topology file. Often such crashes are caused by a wrong, too small MCS. 
> 
> 
> 
> Are you inverting stereocenters? If not, `mcs_type=graph` (the default) should work.
> 
> 
> 
> Note: you seem to be using a SLURM job to run `runall.sh`, but `runall.sh` was written to work with SLURM. Take a look at the manual, setting `output_runbefore` and using `output_scripttype=slurm` may save you some time.

Dear professor, thank you very much for your advice and guidance. I have completed most of the simulation run and have 100gb simulation file, but there is no data in my rerun and analysis folders. May I ask if I can flexibly run the step of rerun alone through the code？

**Comment by Tiamo6174** [comment]
> Your system is unstable. Would you mind checking that the MCS for you pair makes sense? The MCS is printed with verbose output (`-vv`) and can also be checked by inspecting the constant, A and B parts in the ligand topology file. Often such crashes are caused by a wrong, too small MCS. 
> 
> 
> 
> Are you inverting stereocenters? If not, `mcs_type=graph` (the default) should work.
> 
> 
> 
> Note: you seem to be using a SLURM job to run `runall.sh`, but `runall.sh` was written to work with SLURM. Take a look at the manual, setting `output_runbefore` and using `output_scripttype=slurm` may save you some time.

Thanks for your advice and guidance, I have successfully completed my simulation process, and thank you for your contribution to PyAutoFEP work
