### ISSUE TITLE
"There is no domain decomposition for XX ranks" when running nve equilibration.

### ISSUE THREAD

**Issue by xy21hb** [luancarvalhomartins/PyAutoFEP#97]
Dear all,

I am using Gromacs 2019.6 on a single node to run Tutorial, I set "gmx_bin_run=mpirun gmx_mpi" in step2.ini

when running runall.sh on Page 5, it gives the error below, i.e. it cannot pass NVE step, 

![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/14272986/3fe9c07a-59b9-420b-ac5e-ba9d4e07ec4e)

However, if I set "gmx_bin_run=mpirun -np 24 gmx_mpi" in step2.ini, it can go till Rerun step for multiple directory rerunning,
but fails with error "Mpirun does not support recursive call", ....

I wonder how I could set this gmx_bin_run, if it does not specify "-np #", it would lead to errors for domain decomposition and perhaps occupy all the ranks on a single node.

**Comment by luancarvalhomartins** [comment]
1. You should **not** pass `mpirun gmx_mpi` to `gmx_bin_run`. It should point to you `gmx_mpi` binary, nothing else. The run script use that binary to call mpirun so adding mpirun will cause the error.
2. You are trying to run a small system using too many ranks. I see at least two ways of fixing that:
  1. Use SLURM or PBS and set the number of cores per job (this is the "correct" way)
  2. Set `OMP_NUM_THREADS` environment 

What we can do at the code level is run equilibration using `mpirun`. I mentioned this enhancement in #84.

I am opening a enhancement request for that.

**Comment by xy21hb** [comment]
Dear Luan,

I have got error like below. Quite different from previous common errors, I only have errors from the water system leg,
[image]<https://user-images.githubusercontent.com/14272986/253902454-b59d8e2a-c62c-4b4c-8666-e73a82a32823.png>

For each transformation, e.g. FXR_12 ---> FXR_88, I go to /PyAutoFEP-master/docs/tutorial01/tutorial1/FXR_12-FXR_88/water/md,
l can have logs like below, I checked the feprun_... log and reren_joblog_....log, there is no notable error msg inside,
[???? 2023-07-17 174410]<https://user-images.githubusercontent.com/14272986/253904830-27be7bb4-09b3-4e0c-a2fd-addec81fa9ab.jpg>

However, there is nothing in /analysis, there seems to be no traj or analysis generated. Moreover, in /rerun, I can have files like,

[???? 2023-07-17 174329]<https://user-images.githubusercontent.com/14272986/253904875-82fc90c7-b347-43c1-b7b7-ab90f7c3b909.jpg>

However, in the counterpart of protein leg, everything seems to be okay,

[???? 2023-07-17 174556]<https://user-images.githubusercontent.com/14272986/253905275-3e4a8e71-c310-4a53-9e29-2cf33a73c7fc.jpg>

So why does the water leg only have problems, but not protein leg? Thanks!

________________________________

**Comment by luancarvalhomartins** [comment]
From your output, it is not clear what happened. Did `gmx mdrun` run to completion? Are the .xvg files correct?

**Comment by luancarvalhomartins** [comment]
Please, follow the parallelization of equilibration in #104.
